// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace CoreWCF.DataContractSerialization.Generator;

public sealed partial class DataContractSerializerGenerator
{
    /// <summary>
    /// Turns a <see cref="ContextSpec"/> into C# source. Sees no symbols and no compilation.
    /// </summary>
    internal sealed class Emitter
    {
        private const string AotSerializerType = "global::CoreWCF.Runtime.Serialization.AotXmlObjectSerializer";
        private const string XmlDictionaryStringType = "global::System.Xml.XmlDictionaryString";

        private readonly StringBuilder _builder = new();

        internal SourceText Emit(ContextSpec context)
        {
            Indentor indentor = new();

            _builder.AppendLine("// <auto-generated>");
            _builder.AppendLine("// Generated by the CoreWCF.DataContractSerialization source generator. DO NOT EDIT!");
            _builder.AppendLine("// </auto-generated>");
            // The consuming project's nullable setting is not ours to guess at, and generated code
            // that trips a nullable warning would fail builds that treat them as errors.
            _builder.AppendLine("#nullable disable");
            _builder.AppendLine();

            bool hasNamespace = context.Namespace is not null;
            if (hasNamespace)
            {
                _builder.AppendLine($"namespace {context.Namespace}");
                _builder.AppendLine("{");
                indentor.Increment();
            }

            _builder.AppendLine($"{indentor}partial class {context.Name}");
            _builder.AppendLine($"{indentor}{{");
            indentor.Increment();

            EmitGetSerializer(indentor, context);

            indentor.Decrement();
            _builder.AppendLine($"{indentor}}}");

            if (hasNamespace)
            {
                indentor.Decrement();
                _builder.AppendLine("}");
            }

            _builder.AppendLine();
            _builder.AppendLine("#nullable restore");

            return SourceText.From(_builder.ToString(), Encoding.UTF8, SourceHashAlgorithm.Sha256);
        }

        private void EmitGetSerializer(Indentor indentor, ContextSpec context)
        {
            _builder.AppendLine($"{indentor}/// <inheritdoc />");
            _builder.AppendLine($"{indentor}public override {AotSerializerType} GetSerializer(global::System.Type type, {XmlDictionaryStringType} name, {XmlDictionaryStringType} ns)");
            _builder.AppendLine($"{indentor}{{");
            indentor.Increment();

            if (context.Contracts.Count == 0)
            {
                // Returning null is a supported answer, not a failure: CoreWCF falls back to the
                // reflection-based serializer for anything this context does not cover.
                _builder.AppendLine($"{indentor}return null;");
            }
            else
            {
                foreach (ContractSpec contract in context.Contracts)
                {
                    _builder.AppendLine($"{indentor}// {contract.FullyQualifiedName} => {contract.ContractName} ({contract.ContractNamespace})");
                }

                _builder.AppendLine($"{indentor}return null;");
            }

            indentor.Decrement();
            _builder.AppendLine($"{indentor}}}");
        }
    }
}
