// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace CoreWCF.DataContractSerialization.Generator;

public sealed partial class DataContractSerializerGenerator
{
    /// <summary>
    /// Turns a <see cref="ContextSpec"/> into C# source. Sees no symbols and no compilation.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The emitted writer calls mirror dotnet/runtime's ReflectionXmlFormatWriter and
    /// XmlWriterDelegator call for call. That is not stylistic: XmlDictionaryWriter assigns
    /// namespace prefixes as namespaces come into scope, so making the same calls in the same order
    /// reproduces the same prefixes - and the fixtures compare bytes.
    /// </para>
    /// <para>
    /// Each contract emits a static content writer that writes only its members, and a serializer
    /// class that wraps one in a root element. Splitting them is what lets a nested contract member
    /// be written inline - the wire format has no second wrapping element - and lets a derived
    /// contract emit its base's members first by simply calling the base writer.
    /// </para>
    /// </remarks>
    internal sealed class Emitter
    {
        private const string AotSerializer = "global::CoreWCF.Runtime.Serialization.AotXmlObjectSerializer";
        private const string DictionaryString = "global::System.Xml.XmlDictionaryString";
        private const string DictionaryWriter = "global::System.Xml.XmlDictionaryWriter";
        private const string XmlConvert = "global::System.Xml.XmlConvert";
        private const string SchemaInstanceNamespace = "http://www.w3.org/2001/XMLSchema-instance";

        private readonly StringBuilder _builder = new();
        private readonly Dictionary<string, int> _contractIndexes = new(StringComparer.Ordinal);
        private readonly Dictionary<string, int> _enumIndexes = new(StringComparer.Ordinal);
        private readonly Dictionary<string, EnumSpec> _enumSpecs = new(StringComparer.Ordinal);

        internal SourceText Emit(ContextSpec context)
        {
            Indentor indentor = new();

            int index = 0;
            foreach (ContractSpec contract in context.Contracts)
            {
                _contractIndexes[contract.FullyQualifiedName] = index++;
            }

            _builder.AppendLine("// <auto-generated>");
            _builder.AppendLine("// Generated by the CoreWCF.DataContractSerialization source generator. DO NOT EDIT!");
            _builder.AppendLine("// </auto-generated>");
            // The consuming project's nullable setting is not ours to guess at, and generated code
            // that tripped a nullable warning would fail builds that treat warnings as errors.
            _builder.AppendLine("#nullable disable");
            _builder.AppendLine();

            bool hasNamespace = context.Namespace is not null;
            if (hasNamespace)
            {
                _builder.AppendLine($"namespace {context.Namespace}");
                _builder.AppendLine("{");
                indentor.Increment();
            }

            _builder.AppendLine($"{indentor}partial class {context.Name}");
            _builder.AppendLine($"{indentor}{{");
            indentor.Increment();

            int enumIndex = 0;
            foreach (EnumSpec enumSpec in context.Enums)
            {
                _enumIndexes[enumSpec.FullyQualifiedName] = enumIndex++;
                _enumSpecs[enumSpec.FullyQualifiedName] = enumSpec;
            }

            EmitGetSerializer(indentor, context);
            EmitNilHelper(indentor);

            if (context.Enums.Count > 0)
            {
                EmitEnumHelper(indentor);

                foreach (EnumSpec enumSpec in context.Enums)
                {
                    _builder.AppendLine();
                    EmitEnumTable(indentor, enumSpec);
                }
            }

            foreach (ContractSpec contract in context.Contracts)
            {
                if (!contract.IsSupported)
                {
                    continue;
                }

                _builder.AppendLine();
                EmitContentWriter(indentor, contract);

                if (contract.IsRoot)
                {
                    _builder.AppendLine();
                    EmitSerializer(indentor, contract);
                }
            }

            indentor.Decrement();
            _builder.AppendLine($"{indentor}}}");

            if (hasNamespace)
            {
                indentor.Decrement();
                _builder.AppendLine("}");
            }

            _builder.AppendLine();
            _builder.AppendLine("#nullable restore");

            return SourceText.From(_builder.ToString(), Encoding.UTF8, SourceHashAlgorithm.Sha256);
        }

        private void EmitGetSerializer(Indentor indentor, ContextSpec context)
        {
            _builder.AppendLine($"{indentor}/// <inheritdoc />");
            _builder.AppendLine($"{indentor}public override {AotSerializer} GetSerializer(global::System.Type type, {DictionaryString} name, {DictionaryString} ns)");
            _builder.AppendLine($"{indentor}{{");
            indentor.Increment();

            foreach (ContractSpec contract in context.Contracts)
            {
                if (contract.IsSupported && contract.IsRoot)
                {
                    _builder.AppendLine($"{indentor}if (type == typeof({contract.FullyQualifiedName}))");
                    _builder.AppendLine($"{indentor}{{");
                    indentor.Increment();
                    _builder.AppendLine($"{indentor}return new {SerializerTypeName(contract)}(name, ns);");
                    indentor.Decrement();
                    _builder.AppendLine($"{indentor}}}");
                    _builder.AppendLine();
                }
                else if (!contract.IsSupported)
                {
                    // Recorded rather than silently omitted: this list is the coverage report.
                    _builder.AppendLine($"{indentor}// {contract.FullyQualifiedName}: {contract.UnsupportedReason}");
                }
            }

            // Null is a supported answer: CoreWCF falls back to the reflection-based serializer for
            // anything this context does not cover.
            _builder.AppendLine($"{indentor}return null;");

            indentor.Decrement();
            _builder.AppendLine($"{indentor}}}");
        }

        private void EmitSerializer(Indentor indentor, ContractSpec contract)
        {
            string typeName = SerializerTypeName(contract);

            _builder.AppendLine($"{indentor}/// <summary>Writes {contract.ContractName} in {contract.ContractNamespace}.</summary>");
            _builder.AppendLine($"{indentor}private sealed class {typeName} : {AotSerializer}");
            _builder.AppendLine($"{indentor}{{");
            indentor.Increment();

            _builder.AppendLine($"{indentor}private readonly {DictionaryString} _name;");
            _builder.AppendLine($"{indentor}private readonly {DictionaryString} _ns;");
            _builder.AppendLine();
            _builder.AppendLine($"{indentor}internal {typeName}({DictionaryString} name, {DictionaryString} ns)");
            _builder.AppendLine($"{indentor}{{");
            indentor.Increment();
            _builder.AppendLine($"{indentor}_name = name;");
            _builder.AppendLine($"{indentor}_ns = ns;");
            indentor.Decrement();
            _builder.AppendLine($"{indentor}}}");
            _builder.AppendLine();

            _builder.AppendLine($"{indentor}/// <inheritdoc />");
            _builder.AppendLine($"{indentor}public override void WriteObject({DictionaryWriter} writer, object graph)");
            _builder.AppendLine($"{indentor}{{");
            indentor.Increment();

            _builder.AppendLine($"{indentor}writer.WriteStartElement(_name, _ns);");
            _builder.AppendLine();

            // The contract namespace is declared at the root with no prefix, letting the writer
            // allocate one - this is what produces 'a:'. Skipped when it would duplicate the root
            // namespace. Mirrors XmlObjectSerializer.CheckIfNeedsContractNsAtRoot.
            _builder.AppendLine($"{indentor}if (!string.Equals({Literal(contract.ContractNamespace)}, _ns?.Value, global::System.StringComparison.Ordinal))");
            _builder.AppendLine($"{indentor}{{");
            indentor.Increment();
            _builder.AppendLine($"{indentor}writer.WriteXmlnsAttribute(null, {Literal(contract.ContractNamespace)});");
            indentor.Decrement();
            _builder.AppendLine($"{indentor}}}");
            _builder.AppendLine();

            // Declared on every root even when unused, matching
            // XmlObjectSerializerWriteContext.HandleGraphAtTopLevel.
            _builder.AppendLine($"{indentor}writer.WriteXmlnsAttribute(\"i\", {Literal(SchemaInstanceNamespace)});");
            _builder.AppendLine();

            _builder.AppendLine($"{indentor}if (graph == null)");
            _builder.AppendLine($"{indentor}{{");
            indentor.Increment();
            _builder.AppendLine($"{indentor}WriteNil(writer);");
            indentor.Decrement();
            _builder.AppendLine($"{indentor}}}");
            _builder.AppendLine($"{indentor}else");
            _builder.AppendLine($"{indentor}{{");
            indentor.Increment();
            _builder.AppendLine($"{indentor}{ContentWriterName(contract)}(writer, ({contract.FullyQualifiedName})graph);");
            indentor.Decrement();
            _builder.AppendLine($"{indentor}}}");
            _builder.AppendLine();
            _builder.AppendLine($"{indentor}writer.WriteEndElement();");

            indentor.Decrement();
            _builder.AppendLine($"{indentor}}}");

            indentor.Decrement();
            _builder.AppendLine($"{indentor}}}");
        }

        /// <summary>
        /// Emits the method that writes a contract's members, with no wrapping element.
        /// </summary>
        private void EmitContentWriter(Indentor indentor, ContractSpec contract)
        {
            _builder.AppendLine($"{indentor}/// <summary>Writes the members of {contract.ContractName}, without a wrapping element.</summary>");
            _builder.AppendLine($"{indentor}private static void {ContentWriterName(contract)}({DictionaryWriter} writer, {contract.FullyQualifiedName} value)");
            _builder.AppendLine($"{indentor}{{");
            indentor.Increment();

            if (contract.BaseContractFullyQualifiedName is string baseName && _contractIndexes.ContainsKey(baseName))
            {
                // Base members come first, and are ordered within their own contract rather than
                // merged with the derived ones. Mirrors the recursion in
                // ReflectionXmlClassWriter.ReflectionWriteMembers.
                _builder.AppendLine($"{indentor}{ContentWriterName(baseName)}(writer, value);");

                if (contract.Members.Count > 0)
                {
                    _builder.AppendLine();
                }
            }

            if (contract.Members.Count == 0 && contract.BaseContractFullyQualifiedName is null)
            {
                _builder.AppendLine($"{indentor}// no data members");
            }

            bool first = true;
            foreach (MemberSpec member in contract.Members)
            {
                if (!first)
                {
                    _builder.AppendLine();
                }

                first = false;
                EmitMember(indentor, contract, member);
            }

            indentor.Decrement();
            _builder.AppendLine($"{indentor}}}");
        }

        private void EmitMember(Indentor indentor, ContractSpec contract, MemberSpec member)
        {
            string access = "value." + member.MemberName;
            string name = Literal(member.Name);

            _builder.AppendLine($"{indentor}// {member.MemberName} (Order = {member.Order})");

            if (!member.EmitDefaultValue)
            {
                // A member equal to its type's default is omitted entirely - unless it is also
                // required, which DataContractSerializer treats as an error rather than an omission.
                // See ReflectionXmlFormatWriter.ReflectionWriteMembers.
                _builder.AppendLine($"{indentor}if ({IsDefaultExpression(member, access)})");
                _builder.AppendLine($"{indentor}{{");
                indentor.Increment();

                if (member.IsRequired)
                {
                    _builder.AppendLine($"{indentor}throw new global::System.Runtime.Serialization.SerializationException(");
                    indentor.Increment();
                    _builder.AppendLine($"{indentor}\"Member {member.MemberName} is required but is at its default value and EmitDefaultValue is false.\");");
                    indentor.Decrement();
                }
                else
                {
                    _builder.AppendLine($"{indentor}// omitted");
                }

                indentor.Decrement();
                _builder.AppendLine($"{indentor}}}");
                _builder.AppendLine($"{indentor}else");
                _builder.AppendLine($"{indentor}{{");
                indentor.Increment();

                // Reaching this branch already proves the member is not at its default, and for the
                // nullable kinds "default" is exactly "null" - so re-testing for null here would be
                // dead code.
                EmitMemberElement(indentor, contract, member, access, name, nullAlreadyExcluded: true);

                indentor.Decrement();
                _builder.AppendLine($"{indentor}}}");
            }
            else
            {
                EmitMemberElement(indentor, contract, member, access, name, nullAlreadyExcluded: false);
            }
        }

        private void EmitMemberElement(Indentor indentor, ContractSpec contract, MemberSpec member, string access, string name, bool nullAlreadyExcluded)
        {
            bool canBeNull = !nullAlreadyExcluded
                && (member.IsNullableValueType
                    || member.Kind is MemberKind.String or MemberKind.ByteArray or MemberKind.Contract);

            _builder.AppendLine($"{indentor}writer.WriteStartElement({name}, {Literal(contract.ContractNamespace)});");

            // A member whose type lives in a different contract namespace declares it here rather
            // than at the root. Mirrors ClassDataContract.GetChildNamespaceToDeclare, and is what
            // puts xmlns:b on the member element.
            if (member.ChildNamespaceToDeclare is string childNamespace)
            {
                _builder.AppendLine($"{indentor}writer.WriteXmlnsAttribute(null, {Literal(childNamespace)});");
            }

            if (canBeNull)
            {
                string nullTest = member.IsNullableValueType ? $"!{access}.HasValue" : $"{access} == null";
                _builder.AppendLine($"{indentor}if ({nullTest})");
                _builder.AppendLine($"{indentor}{{");
                indentor.Increment();
                _builder.AppendLine($"{indentor}WriteNil(writer);");
                indentor.Decrement();
                _builder.AppendLine($"{indentor}}}");
                _builder.AppendLine($"{indentor}else");
                _builder.AppendLine($"{indentor}{{");
                indentor.Increment();
            }

            string value = member.IsNullableValueType ? access + ".Value" : access;

            if (member.Kind == MemberKind.Contract)
            {
                _builder.AppendLine($"{indentor}{ContentWriterName(member.NestedContractFullyQualifiedName!)}(writer, {value});");
            }
            else if (member.Kind == MemberKind.Enum)
            {
                int index = _enumIndexes[member.NestedContractFullyQualifiedName!];
                EnumSpec spec = _enumSpecs[member.NestedContractFullyQualifiedName!];
                string cast = spec.IsUnsignedLong ? $"unchecked((long)(ulong){value})" : $"(long){value}";
                string isFlags = spec.IsFlags ? "true" : "false";

                _builder.AppendLine($"{indentor}WriteEnum(writer, {cast}, __EnumValues{index}, __EnumNames{index}, {isFlags}, {Literal(member.NestedContractFullyQualifiedName!)});");
            }
            else
            {
                _builder.AppendLine($"{indentor}{WriteValueStatement(member.Kind, value)}");
            }

            if (canBeNull)
            {
                indentor.Decrement();
                _builder.AppendLine($"{indentor}}}");
            }

            _builder.AppendLine($"{indentor}writer.WriteEndElement();");
        }

        /// <summary>
        /// The statement that writes a member's value.
        /// </summary>
        /// <remarks>
        /// Every case here matches XmlWriterDelegator in dotnet/runtime. The non-obvious ones:
        /// char is written as its numeric value, not as a character; Guid and TimeSpan go through
        /// WriteRaw because XmlWriter has no WriteValue overload for them; byte[] is base64.
        /// </remarks>
        private static string WriteValueStatement(MemberKind kind, string value) => kind switch
        {
            MemberKind.Char => $"writer.WriteValue((int){value});",
            MemberKind.Guid => $"writer.WriteRaw({value}.ToString());",
            MemberKind.TimeSpan => $"writer.WriteRaw({XmlConvert}.ToString({value}));",
            MemberKind.ByteArray => $"writer.WriteBase64({value}, 0, {value}.Length);",
            _ => $"writer.WriteValue({value});"
        };

        /// <summary>
        /// The test for "this member is at its type's default", as
        /// <c>EmitDefaultValue = false</c> defines it.
        /// </summary>
        private static string IsDefaultExpression(MemberSpec member, string access)
        {
            if (member.IsNullableValueType)
            {
                return $"!{access}.HasValue";
            }

            return member.Kind switch
            {
                MemberKind.String or MemberKind.ByteArray or MemberKind.Contract => $"{access} == null",
                MemberKind.Boolean => $"!{access}",
                _ => $"{access} == default"
            };
        }

        /// <summary>
        /// Emits the shared enum writer: one copy of the algorithm, driven by a per-enum table.
        /// </summary>
        /// <remarks>
        /// Mirrors EnumDataContract.WriteEnumValue. An exact value match wins even for a flags enum,
        /// which is why the combined value is looked up before any decomposition. A flags value that
        /// cannot be fully decomposed is an error rather than a partial write, and a zero that
        /// matched nothing falls back to the member declared as zero, if there is one.
        /// </remarks>
        private void EmitEnumHelper(Indentor indentor)
        {
            _builder.AppendLine();
            _builder.AppendLine($"{indentor}private static void WriteEnum({DictionaryWriter} writer, long longValue, long[] values, string[] names, bool isFlags, string typeName)");
            _builder.AppendLine($"{indentor}{{");
            indentor.Increment();
            _builder.AppendLine($"{indentor}for (int i = 0; i < values.Length; i++)");
            _builder.AppendLine($"{indentor}{{");
            indentor.Increment();
            _builder.AppendLine($"{indentor}if (longValue == values[i])");
            _builder.AppendLine($"{indentor}{{");
            indentor.Increment();
            _builder.AppendLine($"{indentor}writer.WriteString(names[i]);");
            _builder.AppendLine($"{indentor}return;");
            indentor.Decrement();
            _builder.AppendLine($"{indentor}}}");
            indentor.Decrement();
            _builder.AppendLine($"{indentor}}}");
            _builder.AppendLine();
            _builder.AppendLine($"{indentor}if (isFlags)");
            _builder.AppendLine($"{indentor}{{");
            indentor.Increment();
            _builder.AppendLine($"{indentor}int zeroIndex = -1;");
            _builder.AppendLine($"{indentor}bool noneWritten = true;");
            _builder.AppendLine($"{indentor}for (int i = 0; i < values.Length; i++)");
            _builder.AppendLine($"{indentor}{{");
            indentor.Increment();
            _builder.AppendLine($"{indentor}long current = values[i];");
            _builder.AppendLine($"{indentor}if (current == 0) {{ zeroIndex = i; continue; }}");
            _builder.AppendLine($"{indentor}if (longValue == 0) {{ break; }}");
            _builder.AppendLine($"{indentor}if ((current & longValue) == current)");
            _builder.AppendLine($"{indentor}{{");
            indentor.Increment();
            _builder.AppendLine($"{indentor}if (noneWritten) {{ noneWritten = false; }} else {{ writer.WriteString(\" \"); }}");
            _builder.AppendLine($"{indentor}writer.WriteString(names[i]);");
            _builder.AppendLine($"{indentor}longValue &= ~current;");
            indentor.Decrement();
            _builder.AppendLine($"{indentor}}}");
            indentor.Decrement();
            _builder.AppendLine($"{indentor}}}");
            _builder.AppendLine();
            _builder.AppendLine($"{indentor}if (longValue != 0)");
            _builder.AppendLine($"{indentor}{{");
            indentor.Increment();
            _builder.AppendLine($"{indentor}throw new global::System.Runtime.Serialization.SerializationException(\"Invalid enum value on write for \" + typeName + \".\");");
            indentor.Decrement();
            _builder.AppendLine($"{indentor}}}");
            _builder.AppendLine();
            _builder.AppendLine($"{indentor}if (noneWritten && zeroIndex >= 0)");
            _builder.AppendLine($"{indentor}{{");
            indentor.Increment();
            _builder.AppendLine($"{indentor}writer.WriteString(names[zeroIndex]);");
            indentor.Decrement();
            _builder.AppendLine($"{indentor}}}");
            _builder.AppendLine();
            _builder.AppendLine($"{indentor}return;");
            indentor.Decrement();
            _builder.AppendLine($"{indentor}}}");
            _builder.AppendLine();
            _builder.AppendLine($"{indentor}throw new global::System.Runtime.Serialization.SerializationException(\"Invalid enum value on write for \" + typeName + \".\");");
            indentor.Decrement();
            _builder.AppendLine($"{indentor}}}");
        }

        private void EmitEnumTable(Indentor indentor, EnumSpec enumSpec)
        {
            int index = _enumIndexes[enumSpec.FullyQualifiedName];

            List<string> values = new();
            List<string> names = new();
            foreach (EnumMemberSpec member in enumSpec.Members)
            {
                values.Add(member.Value.ToString(System.Globalization.CultureInfo.InvariantCulture) + "L");
                names.Add(Literal(member.Name));
            }

            _builder.AppendLine($"{indentor}// {enumSpec.FullyQualifiedName}");
            _builder.AppendLine($"{indentor}private static readonly long[] __EnumValues{index} = new long[] {{ {string.Join(", ", values)} }};");
            _builder.AppendLine($"{indentor}private static readonly string[] __EnumNames{index} = new string[] {{ {string.Join(", ", names)} }};");
        }

        private void EmitNilHelper(Indentor indentor)
        {
            _builder.AppendLine();
            _builder.AppendLine($"{indentor}private static void WriteNil({DictionaryWriter} writer)");
            _builder.AppendLine($"{indentor}{{");
            indentor.Increment();
            _builder.AppendLine($"{indentor}writer.WriteAttributeString(\"i\", \"nil\", {Literal(SchemaInstanceNamespace)}, \"true\");");
            indentor.Decrement();
            _builder.AppendLine($"{indentor}}}");
        }

        private string SerializerTypeName(ContractSpec contract) =>
            "__DataContractSerializer" + _contractIndexes[contract.FullyQualifiedName].ToString();

        private string ContentWriterName(ContractSpec contract) => ContentWriterName(contract.FullyQualifiedName);

        private string ContentWriterName(string fullyQualifiedName) =>
            "__WriteContent" + _contractIndexes[fullyQualifiedName].ToString();

        private static string Literal(string value) => "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
    }
}
