// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace CoreWCF.DataContractSerialization.Generator;

public sealed partial class DataContractSerializerGenerator
{
    /// <summary>
    /// Turns a <see cref="ContextSpec"/> into C# source. Sees no symbols and no compilation.
    /// </summary>
    /// <remarks>
    /// The emitted writer calls mirror dotnet/runtime's ReflectionXmlFormatWriter and
    /// XmlWriterDelegator call for call. That is not stylistic: XmlDictionaryWriter assigns
    /// namespace prefixes as namespaces come into scope, so making the same calls in the same order
    /// reproduces the same prefixes - and the fixtures compare bytes.
    /// </remarks>
    internal sealed class Emitter
    {
        private const string AotSerializer = "global::CoreWCF.Runtime.Serialization.AotXmlObjectSerializer";
        private const string DictionaryString = "global::System.Xml.XmlDictionaryString";
        private const string DictionaryWriter = "global::System.Xml.XmlDictionaryWriter";
        private const string XmlConvert = "global::System.Xml.XmlConvert";
        private const string SchemaInstanceNamespace = "http://www.w3.org/2001/XMLSchema-instance";

        private readonly StringBuilder _builder = new();

        internal SourceText Emit(ContextSpec context)
        {
            Indentor indentor = new();

            _builder.AppendLine("// <auto-generated>");
            _builder.AppendLine("// Generated by the CoreWCF.DataContractSerialization source generator. DO NOT EDIT!");
            _builder.AppendLine("// </auto-generated>");
            // The consuming project's nullable setting is not ours to guess at, and generated code
            // that tripped a nullable warning would fail builds that treat warnings as errors.
            _builder.AppendLine("#nullable disable");
            _builder.AppendLine();

            bool hasNamespace = context.Namespace is not null;
            if (hasNamespace)
            {
                _builder.AppendLine($"namespace {context.Namespace}");
                _builder.AppendLine("{");
                indentor.Increment();
            }

            _builder.AppendLine($"{indentor}partial class {context.Name}");
            _builder.AppendLine($"{indentor}{{");
            indentor.Increment();

            EmitGetSerializer(indentor, context);

            int index = 0;
            foreach (ContractSpec contract in context.Contracts)
            {
                if (contract.IsSupported)
                {
                    _builder.AppendLine();
                    EmitSerializer(indentor, contract, index);
                }

                index++;
            }

            indentor.Decrement();
            _builder.AppendLine($"{indentor}}}");

            if (hasNamespace)
            {
                indentor.Decrement();
                _builder.AppendLine("}");
            }

            _builder.AppendLine();
            _builder.AppendLine("#nullable restore");

            return SourceText.From(_builder.ToString(), Encoding.UTF8, SourceHashAlgorithm.Sha256);
        }

        private void EmitGetSerializer(Indentor indentor, ContextSpec context)
        {
            _builder.AppendLine($"{indentor}/// <inheritdoc />");
            _builder.AppendLine($"{indentor}public override {AotSerializer} GetSerializer(global::System.Type type, {DictionaryString} name, {DictionaryString} ns)");
            _builder.AppendLine($"{indentor}{{");
            indentor.Increment();

            int index = 0;
            foreach (ContractSpec contract in context.Contracts)
            {
                if (contract.IsSupported)
                {
                    _builder.AppendLine($"{indentor}if (type == typeof({contract.FullyQualifiedName}))");
                    _builder.AppendLine($"{indentor}{{");
                    indentor.Increment();
                    _builder.AppendLine($"{indentor}return new {SerializerTypeName(index)}(name, ns);");
                    indentor.Decrement();
                    _builder.AppendLine($"{indentor}}}");
                    _builder.AppendLine();
                }
                else
                {
                    // Recorded rather than silently omitted: this list is the coverage report.
                    _builder.AppendLine($"{indentor}// {contract.FullyQualifiedName}: {contract.UnsupportedReason}");
                }

                index++;
            }

            // Null is a supported answer: CoreWCF falls back to the reflection-based serializer for
            // anything this context does not cover.
            _builder.AppendLine($"{indentor}return null;");

            indentor.Decrement();
            _builder.AppendLine($"{indentor}}}");
        }

        private void EmitSerializer(Indentor indentor, ContractSpec contract, int index)
        {
            _builder.AppendLine($"{indentor}/// <summary>Writes {contract.ContractName} in {contract.ContractNamespace}.</summary>");
            _builder.AppendLine($"{indentor}private sealed class {SerializerTypeName(index)} : {AotSerializer}");
            _builder.AppendLine($"{indentor}{{");
            indentor.Increment();

            _builder.AppendLine($"{indentor}private const string ContractNamespace = {Literal(contract.ContractNamespace)};");
            _builder.AppendLine();
            _builder.AppendLine($"{indentor}private readonly {DictionaryString} _name;");
            _builder.AppendLine($"{indentor}private readonly {DictionaryString} _ns;");
            _builder.AppendLine();
            _builder.AppendLine($"{indentor}internal {SerializerTypeName(index)}({DictionaryString} name, {DictionaryString} ns)");
            _builder.AppendLine($"{indentor}{{");
            indentor.Increment();
            _builder.AppendLine($"{indentor}_name = name;");
            _builder.AppendLine($"{indentor}_ns = ns;");
            indentor.Decrement();
            _builder.AppendLine($"{indentor}}}");
            _builder.AppendLine();

            EmitWriteObject(indentor, contract);

            indentor.Decrement();
            _builder.AppendLine($"{indentor}}}");
        }

        private void EmitWriteObject(Indentor indentor, ContractSpec contract)
        {
            _builder.AppendLine($"{indentor}/// <inheritdoc />");
            _builder.AppendLine($"{indentor}public override void WriteObject({DictionaryWriter} writer, object graph)");
            _builder.AppendLine($"{indentor}{{");
            indentor.Increment();

            _builder.AppendLine($"{indentor}writer.WriteStartElement(_name, _ns);");
            _builder.AppendLine();

            // The contract namespace is declared at the root with no prefix, letting the writer
            // allocate one - this is what produces 'a:'. Skipped when it would duplicate the root
            // namespace. Mirrors XmlObjectSerializer.CheckIfNeedsContractNsAtRoot.
            _builder.AppendLine($"{indentor}if (ContractNamespace.Length != 0 && !string.Equals(ContractNamespace, _ns?.Value, global::System.StringComparison.Ordinal))");
            _builder.AppendLine($"{indentor}{{");
            indentor.Increment();
            _builder.AppendLine($"{indentor}writer.WriteXmlnsAttribute(null, ContractNamespace);");
            indentor.Decrement();
            _builder.AppendLine($"{indentor}}}");
            _builder.AppendLine();

            // Declared on every root even when unused, matching
            // XmlObjectSerializerWriteContext.HandleGraphAtTopLevel.
            _builder.AppendLine($"{indentor}writer.WriteXmlnsAttribute(\"i\", {Literal(SchemaInstanceNamespace)});");
            _builder.AppendLine();

            _builder.AppendLine($"{indentor}if (graph == null)");
            _builder.AppendLine($"{indentor}{{");
            indentor.Increment();
            _builder.AppendLine($"{indentor}WriteNil(writer);");
            indentor.Decrement();
            _builder.AppendLine($"{indentor}}}");
            _builder.AppendLine($"{indentor}else");
            _builder.AppendLine($"{indentor}{{");
            indentor.Increment();
            _builder.AppendLine($"{indentor}{contract.FullyQualifiedName} value = ({contract.FullyQualifiedName})graph;");

            foreach (MemberSpec member in contract.Members)
            {
                _builder.AppendLine();
                EmitMember(indentor, member);
            }

            indentor.Decrement();
            _builder.AppendLine($"{indentor}}}");
            _builder.AppendLine();
            _builder.AppendLine($"{indentor}writer.WriteEndElement();");

            indentor.Decrement();
            _builder.AppendLine($"{indentor}}}");
            _builder.AppendLine();

            EmitNilHelper(indentor);
        }

        private void EmitMember(Indentor indentor, MemberSpec member)
        {
            string access = "value." + member.MemberName;
            string name = Literal(member.Name);

            _builder.AppendLine($"{indentor}// {member.MemberName} (Order = {member.Order})");

            if (!member.EmitDefaultValue)
            {
                // A member equal to its type's default is omitted entirely - unless it is also
                // required, which DataContractSerializer treats as an error rather than an omission.
                // See ReflectionXmlFormatWriter.ReflectionWriteMembers.
                string isDefault = IsDefaultExpression(member, access);
                _builder.AppendLine($"{indentor}if ({isDefault})");
                _builder.AppendLine($"{indentor}{{");
                indentor.Increment();

                if (member.IsRequired)
                {
                    _builder.AppendLine($"{indentor}throw new global::System.Runtime.Serialization.SerializationException(");
                    indentor.Increment();
                    _builder.AppendLine($"{indentor}\"Member {member.MemberName} is required but is at its default value and EmitDefaultValue is false.\");");
                    indentor.Decrement();
                }
                else
                {
                    _builder.AppendLine($"{indentor}// omitted");
                }

                indentor.Decrement();
                _builder.AppendLine($"{indentor}}}");
                _builder.AppendLine($"{indentor}else");
                _builder.AppendLine($"{indentor}{{");
                indentor.Increment();

                // Reaching this branch already proves the member is not at its default, and for the
                // nullable kinds "default" is exactly "null" - so re-testing for null here would be
                // dead code.
                EmitMemberElement(indentor, member, access, name, nullAlreadyExcluded: true);

                indentor.Decrement();
                _builder.AppendLine($"{indentor}}}");
            }
            else
            {
                EmitMemberElement(indentor, member, access, name, nullAlreadyExcluded: false);
            }
        }

        private void EmitMemberElement(Indentor indentor, MemberSpec member, string access, string name, bool nullAlreadyExcluded)
        {
            bool canBeNull = !nullAlreadyExcluded
                && (member.IsNullableValueType
                    || member.Kind == MemberKind.String
                    || member.Kind == MemberKind.ByteArray);

            if (canBeNull)
            {
                string nullTest = member.IsNullableValueType ? $"!{access}.HasValue" : $"{access} == null";
                _builder.AppendLine($"{indentor}if ({nullTest})");
                _builder.AppendLine($"{indentor}{{");
                indentor.Increment();
                _builder.AppendLine($"{indentor}writer.WriteStartElement({name}, ContractNamespace);");
                _builder.AppendLine($"{indentor}WriteNil(writer);");
                _builder.AppendLine($"{indentor}writer.WriteEndElement();");
                indentor.Decrement();
                _builder.AppendLine($"{indentor}}}");
                _builder.AppendLine($"{indentor}else");
                _builder.AppendLine($"{indentor}{{");
                indentor.Increment();
            }

            string value = member.IsNullableValueType ? access + ".Value" : access;

            _builder.AppendLine($"{indentor}writer.WriteStartElement({name}, ContractNamespace);");
            _builder.AppendLine($"{indentor}{WriteValueStatement(member.Kind, value)}");
            _builder.AppendLine($"{indentor}writer.WriteEndElement();");

            if (canBeNull)
            {
                indentor.Decrement();
                _builder.AppendLine($"{indentor}}}");
            }
        }

        /// <summary>
        /// The statement that writes a member's value.
        /// </summary>
        /// <remarks>
        /// Every case here matches XmlWriterDelegator in dotnet/runtime. The non-obvious ones:
        /// char is written as its numeric value, not as a character; Guid and TimeSpan go through
        /// WriteRaw because XmlWriter has no WriteValue overload for them; byte[] is base64.
        /// </remarks>
        private static string WriteValueStatement(MemberKind kind, string value) => kind switch
        {
            MemberKind.Char => $"writer.WriteValue((int){value});",
            MemberKind.Guid => $"writer.WriteRaw({value}.ToString());",
            MemberKind.TimeSpan => $"writer.WriteRaw({XmlConvert}.ToString({value}));",
            MemberKind.ByteArray => $"writer.WriteBase64({value}, 0, {value}.Length);",
            _ => $"writer.WriteValue({value});"
        };

        /// <summary>
        /// The test for "this member is at its type's default", as
        /// <c>EmitDefaultValue = false</c> defines it.
        /// </summary>
        private static string IsDefaultExpression(MemberSpec member, string access)
        {
            if (member.IsNullableValueType)
            {
                return $"!{access}.HasValue";
            }

            return member.Kind switch
            {
                MemberKind.String or MemberKind.ByteArray => $"{access} == null",
                MemberKind.Boolean => $"!{access}",
                _ => $"{access} == default"
            };
        }

        private void EmitNilHelper(Indentor indentor)
        {
            _builder.AppendLine($"{indentor}private static void WriteNil({DictionaryWriter} writer)");
            _builder.AppendLine($"{indentor}{{");
            indentor.Increment();
            _builder.AppendLine($"{indentor}writer.WriteAttributeString(\"i\", \"nil\", {Literal(SchemaInstanceNamespace)}, \"true\");");
            indentor.Decrement();
            _builder.AppendLine($"{indentor}}}");
        }

        private static string SerializerTypeName(int index) => $"__DataContractSerializer{index}";

        private static string Literal(string value) => "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
    }
}
