//HintName: App.MyContext.ServiceModelConfiguration.g.cs
// <auto-generated/>
#nullable disable
#pragma warning disable CS1591
#pragma warning disable CS0612, CS0618

namespace App
{
    public partial class MyContext
    {
        private static readonly global::System.Collections.Generic.Dictionary<string, global::System.Type> s_types =
            new global::System.Collections.Generic.Dictionary<string, global::System.Type>(3, global::System.StringComparer.OrdinalIgnoreCase)
            {
                { "CoreWCF.NetTcpBinding", typeof(global::CoreWCF.NetTcpBinding) },
                { "CoreWCF.NetTcpBinding, CoreWCF.NetTcp", typeof(global::CoreWCF.NetTcpBinding) },
                { "netTcp", typeof(global::CoreWCF.NetTcpBinding) },
            };

        public override global::System.Type ResolveType(string name) =>
            name is not null && s_types.TryGetValue(name, out global::System.Type type) ? type : null;

        private static readonly global::System.Collections.Generic.Dictionary<global::System.Type, global::CoreWCF.Extensions.Configuration.ConfiguredType> s_configuredTypes =
            new global::System.Collections.Generic.Dictionary<global::System.Type, global::CoreWCF.Extensions.Configuration.ConfiguredType>(9)
            {
                { typeof(global::CoreWCF.Channels.AddressingVersion), Describe_CoreWCF_Channels_AddressingVersion() },
                { typeof(global::CoreWCF.Channels.MessageVersion), Describe_CoreWCF_Channels_MessageVersion() },
                { typeof(global::CoreWCF.EnvelopeVersion), Describe_CoreWCF_EnvelopeVersion() },
                { typeof(global::CoreWCF.NetTcpBinding), Describe_CoreWCF_NetTcpBinding() },
                { typeof(global::CoreWCF.NetTcpSecurity), Describe_CoreWCF_NetTcpSecurity() },
                { typeof(global::CoreWCF.Security.MessageSecurityOverTcp), Describe_CoreWCF_Security_MessageSecurityOverTcp() },
                { typeof(global::CoreWCF.Security.SecurityAlgorithmSuite), Describe_CoreWCF_Security_SecurityAlgorithmSuite() },
                { typeof(global::CoreWCF.TcpTransportSecurity), Describe_CoreWCF_TcpTransportSecurity() },
                { typeof(global::System.Xml.XmlDictionaryReaderQuotas), Describe_System_Xml_XmlDictionaryReaderQuotas() },
            };

        public override global::CoreWCF.Extensions.Configuration.ConfiguredType GetConfiguredType(global::System.Type type) =>
            type is not null && s_configuredTypes.TryGetValue(type, out global::CoreWCF.Extensions.Configuration.ConfiguredType configured) ? configured : null;

        private static readonly global::System.Collections.Generic.Dictionary<string, global::CoreWCF.Channels.AddressingVersion> s_values_CoreWCF_Channels_AddressingVersion =
            new global::System.Collections.Generic.Dictionary<string, global::CoreWCF.Channels.AddressingVersion>(3, global::System.StringComparer.OrdinalIgnoreCase)
            {
                { "None", global::CoreWCF.Channels.AddressingVersion.None },
                { "WSAddressing10", global::CoreWCF.Channels.AddressingVersion.WSAddressing10 },
                { "WSAddressingAugust2004", global::CoreWCF.Channels.AddressingVersion.WSAddressingAugust2004 },
            };

        private static global::CoreWCF.Extensions.Configuration.ConfiguredType Describe_CoreWCF_Channels_AddressingVersion()
        {
            var members = new global::System.Collections.Generic.Dictionary<string, global::CoreWCF.Extensions.Configuration.ConfiguredMember>(4, global::System.StringComparer.OrdinalIgnoreCase)
            {
                { "Namespace", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("Namespace", typeof(string), static o => (((global::CoreWCF.Channels.AddressingVersion)o).Namespace), null) },
                { "AnonymousUri", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("AnonymousUri", typeof(global::System.Uri), static o => (((global::CoreWCF.Channels.AddressingVersion)o).AnonymousUri), null) },
                { "NoneUri", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("NoneUri", typeof(global::System.Uri), static o => (((global::CoreWCF.Channels.AddressingVersion)o).NoneUri), null) },
                { "FaultAction", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("FaultAction", typeof(string), static o => (((global::CoreWCF.Channels.AddressingVersion)o).FaultAction), null) },
            };

            return new global::CoreWCF.Extensions.Configuration.ConfiguredType(
                typeof(global::CoreWCF.Channels.AddressingVersion),
                create: null,
                members: members,
                parse: static s => s_values_CoreWCF_Channels_AddressingVersion.TryGetValue(s, out global::CoreWCF.Channels.AddressingVersion value) ? (object)value : throw new global::CoreWCF.Extensions.Configuration.BindingConfigurationException($"'{s}' is not a known CoreWCF.Channels.AddressingVersion value."),
                addItem: null,
                itemType: null);
        }

        private static readonly global::System.Collections.Generic.Dictionary<string, global::CoreWCF.Channels.MessageVersion> s_values_CoreWCF_Channels_MessageVersion =
            new global::System.Collections.Generic.Dictionary<string, global::CoreWCF.Channels.MessageVersion>(8, global::System.StringComparer.OrdinalIgnoreCase)
            {
                { "Default", global::CoreWCF.Channels.MessageVersion.Default },
                { "None", global::CoreWCF.Channels.MessageVersion.None },
                { "Soap11", global::CoreWCF.Channels.MessageVersion.Soap11 },
                { "Soap11WSAddressing10", global::CoreWCF.Channels.MessageVersion.Soap11WSAddressing10 },
                { "Soap11WSAddressingAugust2004", global::CoreWCF.Channels.MessageVersion.Soap11WSAddressingAugust2004 },
                { "Soap12", global::CoreWCF.Channels.MessageVersion.Soap12 },
                { "Soap12WSAddressing10", global::CoreWCF.Channels.MessageVersion.Soap12WSAddressing10 },
                { "Soap12WSAddressingAugust2004", global::CoreWCF.Channels.MessageVersion.Soap12WSAddressingAugust2004 },
            };

        private static global::CoreWCF.Extensions.Configuration.ConfiguredType Describe_CoreWCF_Channels_MessageVersion()
        {
            var members = new global::System.Collections.Generic.Dictionary<string, global::CoreWCF.Extensions.Configuration.ConfiguredMember>(2, global::System.StringComparer.OrdinalIgnoreCase)
            {
                { "Addressing", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("Addressing", typeof(global::CoreWCF.Channels.AddressingVersion), static o => (((global::CoreWCF.Channels.MessageVersion)o).Addressing), null) },
                { "Envelope", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("Envelope", typeof(global::CoreWCF.EnvelopeVersion), static o => (((global::CoreWCF.Channels.MessageVersion)o).Envelope), null) },
            };

            return new global::CoreWCF.Extensions.Configuration.ConfiguredType(
                typeof(global::CoreWCF.Channels.MessageVersion),
                create: null,
                members: members,
                parse: static s => s_values_CoreWCF_Channels_MessageVersion.TryGetValue(s, out global::CoreWCF.Channels.MessageVersion value) ? (object)value : throw new global::CoreWCF.Extensions.Configuration.BindingConfigurationException($"'{s}' is not a known CoreWCF.Channels.MessageVersion value."),
                addItem: null,
                itemType: null);
        }

        private static readonly global::System.Collections.Generic.Dictionary<string, global::CoreWCF.EnvelopeVersion> s_values_CoreWCF_EnvelopeVersion =
            new global::System.Collections.Generic.Dictionary<string, global::CoreWCF.EnvelopeVersion>(3, global::System.StringComparer.OrdinalIgnoreCase)
            {
                { "None", global::CoreWCF.EnvelopeVersion.None },
                { "Soap11", global::CoreWCF.EnvelopeVersion.Soap11 },
                { "Soap12", global::CoreWCF.EnvelopeVersion.Soap12 },
            };

        private static global::CoreWCF.Extensions.Configuration.ConfiguredType Describe_CoreWCF_EnvelopeVersion()
        {
            var members = new global::System.Collections.Generic.Dictionary<string, global::CoreWCF.Extensions.Configuration.ConfiguredMember>(3, global::System.StringComparer.OrdinalIgnoreCase)
            {
                { "Namespace", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("Namespace", typeof(string), static o => (((global::CoreWCF.EnvelopeVersion)o).Namespace), null) },
                { "DictionaryNamespace", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("DictionaryNamespace", typeof(global::System.Xml.XmlDictionaryString), static o => (((global::CoreWCF.EnvelopeVersion)o).DictionaryNamespace), null) },
                { "NextDestinationActorValue", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("NextDestinationActorValue", typeof(string), static o => (((global::CoreWCF.EnvelopeVersion)o).NextDestinationActorValue), null) },
            };

            return new global::CoreWCF.Extensions.Configuration.ConfiguredType(
                typeof(global::CoreWCF.EnvelopeVersion),
                create: null,
                members: members,
                parse: static s => s_values_CoreWCF_EnvelopeVersion.TryGetValue(s, out global::CoreWCF.EnvelopeVersion value) ? (object)value : throw new global::CoreWCF.Extensions.Configuration.BindingConfigurationException($"'{s}' is not a known CoreWCF.EnvelopeVersion value."),
                addItem: null,
                itemType: null);
        }

        private static global::CoreWCF.Extensions.Configuration.ConfiguredType Describe_CoreWCF_NetTcpBinding()
        {
            var members = new global::System.Collections.Generic.Dictionary<string, global::CoreWCF.Extensions.Configuration.ConfiguredMember>(18, global::System.StringComparer.OrdinalIgnoreCase)
            {
                { "TransferMode", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("TransferMode", typeof(global::CoreWCF.TransferMode), static o => (((global::CoreWCF.NetTcpBinding)o).TransferMode), static (o, v) => ((global::CoreWCF.NetTcpBinding)o).TransferMode = (global::CoreWCF.TransferMode)v) },
                { "HostNameComparisonMode", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("HostNameComparisonMode", typeof(global::CoreWCF.HostNameComparisonMode), static o => (((global::CoreWCF.NetTcpBinding)o).HostNameComparisonMode), static (o, v) => ((global::CoreWCF.NetTcpBinding)o).HostNameComparisonMode = (global::CoreWCF.HostNameComparisonMode)v) },
                { "MaxBufferPoolSize", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("MaxBufferPoolSize", typeof(long), static o => (((global::CoreWCF.NetTcpBinding)o).MaxBufferPoolSize), static (o, v) => ((global::CoreWCF.NetTcpBinding)o).MaxBufferPoolSize = (long)v) },
                { "MaxBufferSize", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("MaxBufferSize", typeof(int), static o => (((global::CoreWCF.NetTcpBinding)o).MaxBufferSize), static (o, v) => ((global::CoreWCF.NetTcpBinding)o).MaxBufferSize = (int)v) },
                { "MaxConnections", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("MaxConnections", typeof(int), static o => (((global::CoreWCF.NetTcpBinding)o).MaxConnections), static (o, v) => ((global::CoreWCF.NetTcpBinding)o).MaxConnections = (int)v) },
                { "ListenBacklog", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("ListenBacklog", typeof(int), static o => (((global::CoreWCF.NetTcpBinding)o).ListenBacklog), static (o, v) => ((global::CoreWCF.NetTcpBinding)o).ListenBacklog = (int)v) },
                { "MaxReceivedMessageSize", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("MaxReceivedMessageSize", typeof(long), static o => (((global::CoreWCF.NetTcpBinding)o).MaxReceivedMessageSize), static (o, v) => ((global::CoreWCF.NetTcpBinding)o).MaxReceivedMessageSize = (long)v) },
                { "ReaderQuotas", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("ReaderQuotas", typeof(global::System.Xml.XmlDictionaryReaderQuotas), static o => (((global::CoreWCF.NetTcpBinding)o).ReaderQuotas), static (o, v) => ((global::CoreWCF.NetTcpBinding)o).ReaderQuotas = (global::System.Xml.XmlDictionaryReaderQuotas)v) },
                { "Scheme", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("Scheme", typeof(string), static o => (((global::CoreWCF.NetTcpBinding)o).Scheme), null) },
                { "EnvelopeVersion", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("EnvelopeVersion", typeof(global::CoreWCF.EnvelopeVersion), static o => (((global::CoreWCF.NetTcpBinding)o).EnvelopeVersion), null) },
                { "Security", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("Security", typeof(global::CoreWCF.NetTcpSecurity), static o => (((global::CoreWCF.NetTcpBinding)o).Security), static (o, v) => ((global::CoreWCF.NetTcpBinding)o).Security = (global::CoreWCF.NetTcpSecurity)v) },
                { "CloseTimeout", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("CloseTimeout", typeof(global::System.TimeSpan), static o => (((global::CoreWCF.NetTcpBinding)o).CloseTimeout), static (o, v) => ((global::CoreWCF.NetTcpBinding)o).CloseTimeout = (global::System.TimeSpan)v) },
                { "Name", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("Name", typeof(string), static o => (((global::CoreWCF.NetTcpBinding)o).Name), static (o, v) => ((global::CoreWCF.NetTcpBinding)o).Name = (string)v) },
                { "Namespace", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("Namespace", typeof(string), static o => (((global::CoreWCF.NetTcpBinding)o).Namespace), static (o, v) => ((global::CoreWCF.NetTcpBinding)o).Namespace = (string)v) },
                { "OpenTimeout", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("OpenTimeout", typeof(global::System.TimeSpan), static o => (((global::CoreWCF.NetTcpBinding)o).OpenTimeout), static (o, v) => ((global::CoreWCF.NetTcpBinding)o).OpenTimeout = (global::System.TimeSpan)v) },
                { "ReceiveTimeout", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("ReceiveTimeout", typeof(global::System.TimeSpan), static o => (((global::CoreWCF.NetTcpBinding)o).ReceiveTimeout), static (o, v) => ((global::CoreWCF.NetTcpBinding)o).ReceiveTimeout = (global::System.TimeSpan)v) },
                { "MessageVersion", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("MessageVersion", typeof(global::CoreWCF.Channels.MessageVersion), static o => (((global::CoreWCF.NetTcpBinding)o).MessageVersion), null) },
                { "SendTimeout", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("SendTimeout", typeof(global::System.TimeSpan), static o => (((global::CoreWCF.NetTcpBinding)o).SendTimeout), static (o, v) => ((global::CoreWCF.NetTcpBinding)o).SendTimeout = (global::System.TimeSpan)v) },
            };

            return new global::CoreWCF.Extensions.Configuration.ConfiguredType(
                typeof(global::CoreWCF.NetTcpBinding),
                create: static () => new global::CoreWCF.NetTcpBinding(),
                members: members,
                parse: null,
                addItem: null,
                itemType: null);
        }

        private static global::CoreWCF.Extensions.Configuration.ConfiguredType Describe_CoreWCF_NetTcpSecurity()
        {
            var members = new global::System.Collections.Generic.Dictionary<string, global::CoreWCF.Extensions.Configuration.ConfiguredMember>(3, global::System.StringComparer.OrdinalIgnoreCase)
            {
                { "Mode", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("Mode", typeof(global::CoreWCF.SecurityMode), static o => (((global::CoreWCF.NetTcpSecurity)o).Mode), static (o, v) => ((global::CoreWCF.NetTcpSecurity)o).Mode = (global::CoreWCF.SecurityMode)v) },
                { "Transport", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("Transport", typeof(global::CoreWCF.TcpTransportSecurity), static o => (((global::CoreWCF.NetTcpSecurity)o).Transport), static (o, v) => ((global::CoreWCF.NetTcpSecurity)o).Transport = (global::CoreWCF.TcpTransportSecurity)v) },
                { "Message", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("Message", typeof(global::CoreWCF.Security.MessageSecurityOverTcp), static o => (((global::CoreWCF.NetTcpSecurity)o).Message), static (o, v) => ((global::CoreWCF.NetTcpSecurity)o).Message = (global::CoreWCF.Security.MessageSecurityOverTcp)v) },
            };

            return new global::CoreWCF.Extensions.Configuration.ConfiguredType(
                typeof(global::CoreWCF.NetTcpSecurity),
                create: static () => new global::CoreWCF.NetTcpSecurity(),
                members: members,
                parse: null,
                addItem: null,
                itemType: null);
        }

        private static global::CoreWCF.Extensions.Configuration.ConfiguredType Describe_CoreWCF_Security_MessageSecurityOverTcp()
        {
            var members = new global::System.Collections.Generic.Dictionary<string, global::CoreWCF.Extensions.Configuration.ConfiguredMember>(2, global::System.StringComparer.OrdinalIgnoreCase)
            {
                { "ClientCredentialType", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("ClientCredentialType", typeof(global::CoreWCF.MessageCredentialType), static o => (((global::CoreWCF.Security.MessageSecurityOverTcp)o).ClientCredentialType), static (o, v) => ((global::CoreWCF.Security.MessageSecurityOverTcp)o).ClientCredentialType = (global::CoreWCF.MessageCredentialType)v) },
                { "AlgorithmSuite", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("AlgorithmSuite", typeof(global::CoreWCF.Security.SecurityAlgorithmSuite), static o => (((global::CoreWCF.Security.MessageSecurityOverTcp)o).AlgorithmSuite), static (o, v) => ((global::CoreWCF.Security.MessageSecurityOverTcp)o).AlgorithmSuite = (global::CoreWCF.Security.SecurityAlgorithmSuite)v) },
            };

            return new global::CoreWCF.Extensions.Configuration.ConfiguredType(
                typeof(global::CoreWCF.Security.MessageSecurityOverTcp),
                create: static () => new global::CoreWCF.Security.MessageSecurityOverTcp(),
                members: members,
                parse: null,
                addItem: null,
                itemType: null);
        }

        private static readonly global::System.Collections.Generic.Dictionary<string, global::CoreWCF.Security.SecurityAlgorithmSuite> s_values_CoreWCF_Security_SecurityAlgorithmSuite =
            new global::System.Collections.Generic.Dictionary<string, global::CoreWCF.Security.SecurityAlgorithmSuite>(17, global::System.StringComparer.OrdinalIgnoreCase)
            {
                { "Basic128", global::CoreWCF.Security.SecurityAlgorithmSuite.Basic128 },
                { "Basic128Rsa15", global::CoreWCF.Security.SecurityAlgorithmSuite.Basic128Rsa15 },
                { "Basic128Sha256", global::CoreWCF.Security.SecurityAlgorithmSuite.Basic128Sha256 },
                { "Basic128Sha256Rsa15", global::CoreWCF.Security.SecurityAlgorithmSuite.Basic128Sha256Rsa15 },
                { "Basic192", global::CoreWCF.Security.SecurityAlgorithmSuite.Basic192 },
                { "Basic192Rsa15", global::CoreWCF.Security.SecurityAlgorithmSuite.Basic192Rsa15 },
                { "Basic192Sha256", global::CoreWCF.Security.SecurityAlgorithmSuite.Basic192Sha256 },
                { "Basic192Sha256Rsa15", global::CoreWCF.Security.SecurityAlgorithmSuite.Basic192Sha256Rsa15 },
                { "Basic256", global::CoreWCF.Security.SecurityAlgorithmSuite.Basic256 },
                { "Basic256Rsa15", global::CoreWCF.Security.SecurityAlgorithmSuite.Basic256Rsa15 },
                { "Basic256Sha256", global::CoreWCF.Security.SecurityAlgorithmSuite.Basic256Sha256 },
                { "Basic256Sha256Rsa15", global::CoreWCF.Security.SecurityAlgorithmSuite.Basic256Sha256Rsa15 },
                { "Default", global::CoreWCF.Security.SecurityAlgorithmSuite.Default },
                { "TripleDes", global::CoreWCF.Security.SecurityAlgorithmSuite.TripleDes },
                { "TripleDesRsa15", global::CoreWCF.Security.SecurityAlgorithmSuite.TripleDesRsa15 },
                { "TripleDesSha256", global::CoreWCF.Security.SecurityAlgorithmSuite.TripleDesSha256 },
                { "TripleDesSha256Rsa15", global::CoreWCF.Security.SecurityAlgorithmSuite.TripleDesSha256Rsa15 },
            };

        private static global::CoreWCF.Extensions.Configuration.ConfiguredType Describe_CoreWCF_Security_SecurityAlgorithmSuite()
        {
            var members = new global::System.Collections.Generic.Dictionary<string, global::CoreWCF.Extensions.Configuration.ConfiguredMember>(10, global::System.StringComparer.OrdinalIgnoreCase)
            {
                { "DefaultCanonicalizationAlgorithm", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("DefaultCanonicalizationAlgorithm", typeof(string), static o => (((global::CoreWCF.Security.SecurityAlgorithmSuite)o).DefaultCanonicalizationAlgorithm), null) },
                { "DefaultDigestAlgorithm", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("DefaultDigestAlgorithm", typeof(string), static o => (((global::CoreWCF.Security.SecurityAlgorithmSuite)o).DefaultDigestAlgorithm), null) },
                { "DefaultEncryptionAlgorithm", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("DefaultEncryptionAlgorithm", typeof(string), static o => (((global::CoreWCF.Security.SecurityAlgorithmSuite)o).DefaultEncryptionAlgorithm), null) },
                { "DefaultEncryptionKeyDerivationLength", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("DefaultEncryptionKeyDerivationLength", typeof(int), static o => (((global::CoreWCF.Security.SecurityAlgorithmSuite)o).DefaultEncryptionKeyDerivationLength), null) },
                { "DefaultSymmetricKeyWrapAlgorithm", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("DefaultSymmetricKeyWrapAlgorithm", typeof(string), static o => (((global::CoreWCF.Security.SecurityAlgorithmSuite)o).DefaultSymmetricKeyWrapAlgorithm), null) },
                { "DefaultAsymmetricKeyWrapAlgorithm", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("DefaultAsymmetricKeyWrapAlgorithm", typeof(string), static o => (((global::CoreWCF.Security.SecurityAlgorithmSuite)o).DefaultAsymmetricKeyWrapAlgorithm), null) },
                { "DefaultSymmetricSignatureAlgorithm", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("DefaultSymmetricSignatureAlgorithm", typeof(string), static o => (((global::CoreWCF.Security.SecurityAlgorithmSuite)o).DefaultSymmetricSignatureAlgorithm), null) },
                { "DefaultAsymmetricSignatureAlgorithm", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("DefaultAsymmetricSignatureAlgorithm", typeof(string), static o => (((global::CoreWCF.Security.SecurityAlgorithmSuite)o).DefaultAsymmetricSignatureAlgorithm), null) },
                { "DefaultSignatureKeyDerivationLength", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("DefaultSignatureKeyDerivationLength", typeof(int), static o => (((global::CoreWCF.Security.SecurityAlgorithmSuite)o).DefaultSignatureKeyDerivationLength), null) },
                { "DefaultSymmetricKeyLength", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("DefaultSymmetricKeyLength", typeof(int), static o => (((global::CoreWCF.Security.SecurityAlgorithmSuite)o).DefaultSymmetricKeyLength), null) },
            };

            return new global::CoreWCF.Extensions.Configuration.ConfiguredType(
                typeof(global::CoreWCF.Security.SecurityAlgorithmSuite),
                create: null,
                members: members,
                parse: static s => s_values_CoreWCF_Security_SecurityAlgorithmSuite.TryGetValue(s, out global::CoreWCF.Security.SecurityAlgorithmSuite value) ? (object)value : throw new global::CoreWCF.Extensions.Configuration.BindingConfigurationException($"'{s}' is not a known CoreWCF.Security.SecurityAlgorithmSuite value."),
                addItem: null,
                itemType: null);
        }

        private static global::CoreWCF.Extensions.Configuration.ConfiguredType Describe_CoreWCF_TcpTransportSecurity()
        {
            var members = new global::System.Collections.Generic.Dictionary<string, global::CoreWCF.Extensions.Configuration.ConfiguredMember>(1, global::System.StringComparer.OrdinalIgnoreCase)
            {
                { "ClientCredentialType", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("ClientCredentialType", typeof(global::CoreWCF.TcpClientCredentialType), static o => (((global::CoreWCF.TcpTransportSecurity)o).ClientCredentialType), static (o, v) => ((global::CoreWCF.TcpTransportSecurity)o).ClientCredentialType = (global::CoreWCF.TcpClientCredentialType)v) },
            };

            return new global::CoreWCF.Extensions.Configuration.ConfiguredType(
                typeof(global::CoreWCF.TcpTransportSecurity),
                create: static () => new global::CoreWCF.TcpTransportSecurity(),
                members: members,
                parse: null,
                addItem: null,
                itemType: null);
        }

        private static readonly global::System.Collections.Generic.Dictionary<string, global::System.Xml.XmlDictionaryReaderQuotas> s_values_System_Xml_XmlDictionaryReaderQuotas =
            new global::System.Collections.Generic.Dictionary<string, global::System.Xml.XmlDictionaryReaderQuotas>(1, global::System.StringComparer.OrdinalIgnoreCase)
            {
                { "Max", global::System.Xml.XmlDictionaryReaderQuotas.Max },
            };

        private static global::CoreWCF.Extensions.Configuration.ConfiguredType Describe_System_Xml_XmlDictionaryReaderQuotas()
        {
            var members = new global::System.Collections.Generic.Dictionary<string, global::CoreWCF.Extensions.Configuration.ConfiguredMember>(6, global::System.StringComparer.OrdinalIgnoreCase)
            {
                { "MaxStringContentLength", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("MaxStringContentLength", typeof(int), static o => (((global::System.Xml.XmlDictionaryReaderQuotas)o).MaxStringContentLength), static (o, v) => ((global::System.Xml.XmlDictionaryReaderQuotas)o).MaxStringContentLength = (int)v) },
                { "MaxArrayLength", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("MaxArrayLength", typeof(int), static o => (((global::System.Xml.XmlDictionaryReaderQuotas)o).MaxArrayLength), static (o, v) => ((global::System.Xml.XmlDictionaryReaderQuotas)o).MaxArrayLength = (int)v) },
                { "MaxBytesPerRead", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("MaxBytesPerRead", typeof(int), static o => (((global::System.Xml.XmlDictionaryReaderQuotas)o).MaxBytesPerRead), static (o, v) => ((global::System.Xml.XmlDictionaryReaderQuotas)o).MaxBytesPerRead = (int)v) },
                { "MaxDepth", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("MaxDepth", typeof(int), static o => (((global::System.Xml.XmlDictionaryReaderQuotas)o).MaxDepth), static (o, v) => ((global::System.Xml.XmlDictionaryReaderQuotas)o).MaxDepth = (int)v) },
                { "MaxNameTableCharCount", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("MaxNameTableCharCount", typeof(int), static o => (((global::System.Xml.XmlDictionaryReaderQuotas)o).MaxNameTableCharCount), static (o, v) => ((global::System.Xml.XmlDictionaryReaderQuotas)o).MaxNameTableCharCount = (int)v) },
                { "ModifiedQuotas", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("ModifiedQuotas", typeof(global::System.Xml.XmlDictionaryReaderQuotaTypes), static o => (((global::System.Xml.XmlDictionaryReaderQuotas)o).ModifiedQuotas), null) },
            };

            return new global::CoreWCF.Extensions.Configuration.ConfiguredType(
                typeof(global::System.Xml.XmlDictionaryReaderQuotas),
                create: static () => new global::System.Xml.XmlDictionaryReaderQuotas(),
                members: members,
                parse: static s => s_values_System_Xml_XmlDictionaryReaderQuotas.TryGetValue(s, out global::System.Xml.XmlDictionaryReaderQuotas value) ? (object)value : throw new global::CoreWCF.Extensions.Configuration.BindingConfigurationException($"'{s}' is not a known System.Xml.XmlDictionaryReaderQuotas value."),
                addItem: null,
                itemType: null);
        }

    }
}
