//HintName: App.MyContext.ServiceModelConfiguration.g.cs
// <auto-generated/>
#nullable disable
#pragma warning disable CS1591
#pragma warning disable CS0612, CS0618

namespace App
{
    public partial class MyContext
    {
        private static readonly global::System.Collections.Generic.Dictionary<string, global::System.Type> s_types =
            new global::System.Collections.Generic.Dictionary<string, global::System.Type>(9, global::System.StringComparer.OrdinalIgnoreCase)
            {
                { "CoreWCF.Channels.CustomBinding", typeof(global::CoreWCF.Channels.CustomBinding) },
                { "CoreWCF.Channels.CustomBinding, CoreWCF.Primitives", typeof(global::CoreWCF.Channels.CustomBinding) },
                { "CoreWCF.Channels.HttpTransportBindingElement", typeof(global::CoreWCF.Channels.HttpTransportBindingElement) },
                { "CoreWCF.Channels.HttpTransportBindingElement, CoreWCF.Http", typeof(global::CoreWCF.Channels.HttpTransportBindingElement) },
                { "CoreWCF.Channels.TextMessageEncodingBindingElement", typeof(global::CoreWCF.Channels.TextMessageEncodingBindingElement) },
                { "CoreWCF.Channels.TextMessageEncodingBindingElement, CoreWCF.Primitives", typeof(global::CoreWCF.Channels.TextMessageEncodingBindingElement) },
                { "custom", typeof(global::CoreWCF.Channels.CustomBinding) },
                { "httpTransport", typeof(global::CoreWCF.Channels.HttpTransportBindingElement) },
                { "textEncoding", typeof(global::CoreWCF.Channels.TextMessageEncodingBindingElement) },
            };

        public override global::System.Type ResolveType(string name) =>
            name is not null && s_types.TryGetValue(name, out global::System.Type type) ? type : null;

        private static readonly global::System.Collections.Generic.Dictionary<global::System.Type, global::CoreWCF.Extensions.Configuration.ConfiguredType> s_configuredTypes =
            new global::System.Collections.Generic.Dictionary<global::System.Type, global::CoreWCF.Extensions.Configuration.ConfiguredType>(10)
            {
                { typeof(global::CoreWCF.Channels.AddressingVersion), Describe_CoreWCF_Channels_AddressingVersion() },
                { typeof(global::CoreWCF.Channels.BindingElement), Describe_CoreWCF_Channels_BindingElement() },
                { typeof(global::CoreWCF.Channels.BindingElementCollection), Describe_CoreWCF_Channels_BindingElementCollection() },
                { typeof(global::CoreWCF.Channels.CustomBinding), Describe_CoreWCF_Channels_CustomBinding() },
                { typeof(global::CoreWCF.Channels.HttpTransportBindingElement), Describe_CoreWCF_Channels_HttpTransportBindingElement() },
                { typeof(global::CoreWCF.Channels.MessageVersion), Describe_CoreWCF_Channels_MessageVersion() },
                { typeof(global::CoreWCF.Channels.TextMessageEncodingBindingElement), Describe_CoreWCF_Channels_TextMessageEncodingBindingElement() },
                { typeof(global::CoreWCF.Channels.WebSocketTransportSettings), Describe_CoreWCF_Channels_WebSocketTransportSettings() },
                { typeof(global::CoreWCF.EnvelopeVersion), Describe_CoreWCF_EnvelopeVersion() },
                { typeof(global::System.Xml.XmlDictionaryReaderQuotas), Describe_System_Xml_XmlDictionaryReaderQuotas() },
            };

        public override global::CoreWCF.Extensions.Configuration.ConfiguredType GetConfiguredType(global::System.Type type) =>
            type is not null && s_configuredTypes.TryGetValue(type, out global::CoreWCF.Extensions.Configuration.ConfiguredType configured) ? configured : null;

        private static readonly global::System.Collections.Generic.Dictionary<string, global::CoreWCF.Channels.AddressingVersion> s_values_CoreWCF_Channels_AddressingVersion =
            new global::System.Collections.Generic.Dictionary<string, global::CoreWCF.Channels.AddressingVersion>(3, global::System.StringComparer.OrdinalIgnoreCase)
            {
                { "None", global::CoreWCF.Channels.AddressingVersion.None },
                { "WSAddressing10", global::CoreWCF.Channels.AddressingVersion.WSAddressing10 },
                { "WSAddressingAugust2004", global::CoreWCF.Channels.AddressingVersion.WSAddressingAugust2004 },
            };

        private static global::CoreWCF.Extensions.Configuration.ConfiguredType Describe_CoreWCF_Channels_AddressingVersion()
        {
            var members = new global::System.Collections.Generic.Dictionary<string, global::CoreWCF.Extensions.Configuration.ConfiguredMember>(4, global::System.StringComparer.OrdinalIgnoreCase)
            {
                { "Namespace", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("Namespace", typeof(string), static o => (((global::CoreWCF.Channels.AddressingVersion)o).Namespace), null) },
                { "AnonymousUri", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("AnonymousUri", typeof(global::System.Uri), static o => (((global::CoreWCF.Channels.AddressingVersion)o).AnonymousUri), null) },
                { "NoneUri", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("NoneUri", typeof(global::System.Uri), static o => (((global::CoreWCF.Channels.AddressingVersion)o).NoneUri), null) },
                { "FaultAction", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("FaultAction", typeof(string), static o => (((global::CoreWCF.Channels.AddressingVersion)o).FaultAction), null) },
            };

            return new global::CoreWCF.Extensions.Configuration.ConfiguredType(
                typeof(global::CoreWCF.Channels.AddressingVersion),
                create: null,
                members: members,
                parse: static s => s_values_CoreWCF_Channels_AddressingVersion.TryGetValue(s, out global::CoreWCF.Channels.AddressingVersion value) ? (object)value : throw new global::CoreWCF.Extensions.Configuration.BindingConfigurationException($"'{s}' is not a known CoreWCF.Channels.AddressingVersion value."),
                addItem: null,
                itemType: null);
        }

        private static global::CoreWCF.Extensions.Configuration.ConfiguredType Describe_CoreWCF_Channels_BindingElement()
        {
            var members = new global::System.Collections.Generic.Dictionary<string, global::CoreWCF.Extensions.Configuration.ConfiguredMember>(0, global::System.StringComparer.OrdinalIgnoreCase)
            {
            };

            return new global::CoreWCF.Extensions.Configuration.ConfiguredType(
                typeof(global::CoreWCF.Channels.BindingElement),
                create: null,
                members: members,
                parse: null,
                addItem: null,
                itemType: null);
        }

        private static global::CoreWCF.Extensions.Configuration.ConfiguredType Describe_CoreWCF_Channels_BindingElementCollection()
        {
            var members = new global::System.Collections.Generic.Dictionary<string, global::CoreWCF.Extensions.Configuration.ConfiguredMember>(1, global::System.StringComparer.OrdinalIgnoreCase)
            {
                { "Count", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("Count", typeof(int), static o => (((global::CoreWCF.Channels.BindingElementCollection)o).Count), null) },
            };

            return new global::CoreWCF.Extensions.Configuration.ConfiguredType(
                typeof(global::CoreWCF.Channels.BindingElementCollection),
                create: static () => new global::CoreWCF.Channels.BindingElementCollection(),
                members: members,
                parse: null,
                addItem: static (c, i) => ((global::System.Collections.Generic.ICollection<global::CoreWCF.Channels.BindingElement>)c).Add((global::CoreWCF.Channels.BindingElement)i),
                itemType: typeof(global::CoreWCF.Channels.BindingElement));
        }

        private static global::CoreWCF.Extensions.Configuration.ConfiguredType Describe_CoreWCF_Channels_CustomBinding()
        {
            var members = new global::System.Collections.Generic.Dictionary<string, global::CoreWCF.Extensions.Configuration.ConfiguredMember>(9, global::System.StringComparer.OrdinalIgnoreCase)
            {
                { "Elements", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("Elements", typeof(global::CoreWCF.Channels.BindingElementCollection), static o => (((global::CoreWCF.Channels.CustomBinding)o).Elements), null) },
                { "Scheme", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("Scheme", typeof(string), static o => (((global::CoreWCF.Channels.CustomBinding)o).Scheme), null) },
                { "CloseTimeout", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("CloseTimeout", typeof(global::System.TimeSpan), static o => (((global::CoreWCF.Channels.CustomBinding)o).CloseTimeout), static (o, v) => ((global::CoreWCF.Channels.CustomBinding)o).CloseTimeout = (global::System.TimeSpan)v) },
                { "Name", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("Name", typeof(string), static o => (((global::CoreWCF.Channels.CustomBinding)o).Name), static (o, v) => ((global::CoreWCF.Channels.CustomBinding)o).Name = (string)v) },
                { "Namespace", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("Namespace", typeof(string), static o => (((global::CoreWCF.Channels.CustomBinding)o).Namespace), static (o, v) => ((global::CoreWCF.Channels.CustomBinding)o).Namespace = (string)v) },
                { "OpenTimeout", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("OpenTimeout", typeof(global::System.TimeSpan), static o => (((global::CoreWCF.Channels.CustomBinding)o).OpenTimeout), static (o, v) => ((global::CoreWCF.Channels.CustomBinding)o).OpenTimeout = (global::System.TimeSpan)v) },
                { "ReceiveTimeout", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("ReceiveTimeout", typeof(global::System.TimeSpan), static o => (((global::CoreWCF.Channels.CustomBinding)o).ReceiveTimeout), static (o, v) => ((global::CoreWCF.Channels.CustomBinding)o).ReceiveTimeout = (global::System.TimeSpan)v) },
                { "MessageVersion", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("MessageVersion", typeof(global::CoreWCF.Channels.MessageVersion), static o => (((global::CoreWCF.Channels.CustomBinding)o).MessageVersion), null) },
                { "SendTimeout", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("SendTimeout", typeof(global::System.TimeSpan), static o => (((global::CoreWCF.Channels.CustomBinding)o).SendTimeout), static (o, v) => ((global::CoreWCF.Channels.CustomBinding)o).SendTimeout = (global::System.TimeSpan)v) },
            };

            return new global::CoreWCF.Extensions.Configuration.ConfiguredType(
                typeof(global::CoreWCF.Channels.CustomBinding),
                create: static () => new global::CoreWCF.Channels.CustomBinding(),
                members: members,
                parse: null,
                addItem: null,
                itemType: null);
        }

        private static global::CoreWCF.Extensions.Configuration.ConfiguredType Describe_CoreWCF_Channels_HttpTransportBindingElement()
        {
            var members = new global::System.Collections.Generic.Dictionary<string, global::CoreWCF.Extensions.Configuration.ConfiguredMember>(10, global::System.StringComparer.OrdinalIgnoreCase)
            {
                { "AlwaysUseAuthorizationPolicySupport", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("AlwaysUseAuthorizationPolicySupport", typeof(bool), static o => (((global::CoreWCF.Channels.HttpTransportBindingElement)o).AlwaysUseAuthorizationPolicySupport), static (o, v) => ((global::CoreWCF.Channels.HttpTransportBindingElement)o).AlwaysUseAuthorizationPolicySupport = (bool)v) },
                { "MaxBufferSize", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("MaxBufferSize", typeof(int), static o => (((global::CoreWCF.Channels.HttpTransportBindingElement)o).MaxBufferSize), static (o, v) => ((global::CoreWCF.Channels.HttpTransportBindingElement)o).MaxBufferSize = (int)v) },
                { "KeepAliveEnabled", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("KeepAliveEnabled", typeof(bool), static o => (((global::CoreWCF.Channels.HttpTransportBindingElement)o).KeepAliveEnabled), static (o, v) => ((global::CoreWCF.Channels.HttpTransportBindingElement)o).KeepAliveEnabled = (bool)v) },
                { "Realm", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("Realm", typeof(string), static o => (((global::CoreWCF.Channels.HttpTransportBindingElement)o).Realm), static (o, v) => ((global::CoreWCF.Channels.HttpTransportBindingElement)o).Realm = (string)v) },
                { "Scheme", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("Scheme", typeof(string), static o => (((global::CoreWCF.Channels.HttpTransportBindingElement)o).Scheme), null) },
                { "TransferMode", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("TransferMode", typeof(global::CoreWCF.TransferMode), static o => (((global::CoreWCF.Channels.HttpTransportBindingElement)o).TransferMode), static (o, v) => ((global::CoreWCF.Channels.HttpTransportBindingElement)o).TransferMode = (global::CoreWCF.TransferMode)v) },
                { "WebSocketSettings", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("WebSocketSettings", typeof(global::CoreWCF.Channels.WebSocketTransportSettings), static o => (((global::CoreWCF.Channels.HttpTransportBindingElement)o).WebSocketSettings), static (o, v) => ((global::CoreWCF.Channels.HttpTransportBindingElement)o).WebSocketSettings = (global::CoreWCF.Channels.WebSocketTransportSettings)v) },
                { "ManualAddressing", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("ManualAddressing", typeof(bool), static o => (((global::CoreWCF.Channels.HttpTransportBindingElement)o).ManualAddressing), static (o, v) => ((global::CoreWCF.Channels.HttpTransportBindingElement)o).ManualAddressing = (bool)v) },
                { "MaxBufferPoolSize", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("MaxBufferPoolSize", typeof(long), static o => (((global::CoreWCF.Channels.HttpTransportBindingElement)o).MaxBufferPoolSize), static (o, v) => ((global::CoreWCF.Channels.HttpTransportBindingElement)o).MaxBufferPoolSize = (long)v) },
                { "MaxReceivedMessageSize", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("MaxReceivedMessageSize", typeof(long), static o => (((global::CoreWCF.Channels.HttpTransportBindingElement)o).MaxReceivedMessageSize), static (o, v) => ((global::CoreWCF.Channels.HttpTransportBindingElement)o).MaxReceivedMessageSize = (long)v) },
            };

            return new global::CoreWCF.Extensions.Configuration.ConfiguredType(
                typeof(global::CoreWCF.Channels.HttpTransportBindingElement),
                create: static () => new global::CoreWCF.Channels.HttpTransportBindingElement(),
                members: members,
                parse: null,
                addItem: null,
                itemType: null);
        }

        private static readonly global::System.Collections.Generic.Dictionary<string, global::CoreWCF.Channels.MessageVersion> s_values_CoreWCF_Channels_MessageVersion =
            new global::System.Collections.Generic.Dictionary<string, global::CoreWCF.Channels.MessageVersion>(8, global::System.StringComparer.OrdinalIgnoreCase)
            {
                { "Default", global::CoreWCF.Channels.MessageVersion.Default },
                { "None", global::CoreWCF.Channels.MessageVersion.None },
                { "Soap11", global::CoreWCF.Channels.MessageVersion.Soap11 },
                { "Soap11WSAddressing10", global::CoreWCF.Channels.MessageVersion.Soap11WSAddressing10 },
                { "Soap11WSAddressingAugust2004", global::CoreWCF.Channels.MessageVersion.Soap11WSAddressingAugust2004 },
                { "Soap12", global::CoreWCF.Channels.MessageVersion.Soap12 },
                { "Soap12WSAddressing10", global::CoreWCF.Channels.MessageVersion.Soap12WSAddressing10 },
                { "Soap12WSAddressingAugust2004", global::CoreWCF.Channels.MessageVersion.Soap12WSAddressingAugust2004 },
            };

        private static global::CoreWCF.Extensions.Configuration.ConfiguredType Describe_CoreWCF_Channels_MessageVersion()
        {
            var members = new global::System.Collections.Generic.Dictionary<string, global::CoreWCF.Extensions.Configuration.ConfiguredMember>(2, global::System.StringComparer.OrdinalIgnoreCase)
            {
                { "Addressing", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("Addressing", typeof(global::CoreWCF.Channels.AddressingVersion), static o => (((global::CoreWCF.Channels.MessageVersion)o).Addressing), null) },
                { "Envelope", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("Envelope", typeof(global::CoreWCF.EnvelopeVersion), static o => (((global::CoreWCF.Channels.MessageVersion)o).Envelope), null) },
            };

            return new global::CoreWCF.Extensions.Configuration.ConfiguredType(
                typeof(global::CoreWCF.Channels.MessageVersion),
                create: null,
                members: members,
                parse: static s => s_values_CoreWCF_Channels_MessageVersion.TryGetValue(s, out global::CoreWCF.Channels.MessageVersion value) ? (object)value : throw new global::CoreWCF.Extensions.Configuration.BindingConfigurationException($"'{s}' is not a known CoreWCF.Channels.MessageVersion value."),
                addItem: null,
                itemType: null);
        }

        private static global::CoreWCF.Extensions.Configuration.ConfiguredType Describe_CoreWCF_Channels_TextMessageEncodingBindingElement()
        {
            var members = new global::System.Collections.Generic.Dictionary<string, global::CoreWCF.Extensions.Configuration.ConfiguredMember>(5, global::System.StringComparer.OrdinalIgnoreCase)
            {
                { "MaxReadPoolSize", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("MaxReadPoolSize", typeof(int), static o => (((global::CoreWCF.Channels.TextMessageEncodingBindingElement)o).MaxReadPoolSize), static (o, v) => ((global::CoreWCF.Channels.TextMessageEncodingBindingElement)o).MaxReadPoolSize = (int)v) },
                { "MaxWritePoolSize", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("MaxWritePoolSize", typeof(int), static o => (((global::CoreWCF.Channels.TextMessageEncodingBindingElement)o).MaxWritePoolSize), static (o, v) => ((global::CoreWCF.Channels.TextMessageEncodingBindingElement)o).MaxWritePoolSize = (int)v) },
                { "ReaderQuotas", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("ReaderQuotas", typeof(global::System.Xml.XmlDictionaryReaderQuotas), static o => (((global::CoreWCF.Channels.TextMessageEncodingBindingElement)o).ReaderQuotas), static (o, v) => ((global::CoreWCF.Channels.TextMessageEncodingBindingElement)o).ReaderQuotas = (global::System.Xml.XmlDictionaryReaderQuotas)v) },
                { "MessageVersion", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("MessageVersion", typeof(global::CoreWCF.Channels.MessageVersion), static o => (((global::CoreWCF.Channels.TextMessageEncodingBindingElement)o).MessageVersion), static (o, v) => ((global::CoreWCF.Channels.TextMessageEncodingBindingElement)o).MessageVersion = (global::CoreWCF.Channels.MessageVersion)v) },
                { "WriteEncoding", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("WriteEncoding", typeof(global::System.Text.Encoding), static o => (((global::CoreWCF.Channels.TextMessageEncodingBindingElement)o).WriteEncoding), static (o, v) => ((global::CoreWCF.Channels.TextMessageEncodingBindingElement)o).WriteEncoding = (global::System.Text.Encoding)v) },
            };

            return new global::CoreWCF.Extensions.Configuration.ConfiguredType(
                typeof(global::CoreWCF.Channels.TextMessageEncodingBindingElement),
                create: static () => new global::CoreWCF.Channels.TextMessageEncodingBindingElement(),
                members: members,
                parse: null,
                addItem: null,
                itemType: null);
        }

        private static global::CoreWCF.Extensions.Configuration.ConfiguredType Describe_CoreWCF_Channels_WebSocketTransportSettings()
        {
            var members = new global::System.Collections.Generic.Dictionary<string, global::CoreWCF.Extensions.Configuration.ConfiguredMember>(6, global::System.StringComparer.OrdinalIgnoreCase)
            {
                { "TransportUsage", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("TransportUsage", typeof(global::CoreWCF.Channels.WebSocketTransportUsage), static o => (((global::CoreWCF.Channels.WebSocketTransportSettings)o).TransportUsage), static (o, v) => ((global::CoreWCF.Channels.WebSocketTransportSettings)o).TransportUsage = (global::CoreWCF.Channels.WebSocketTransportUsage)v) },
                { "CreateNotificationOnConnection", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("CreateNotificationOnConnection", typeof(bool), static o => (((global::CoreWCF.Channels.WebSocketTransportSettings)o).CreateNotificationOnConnection), static (o, v) => ((global::CoreWCF.Channels.WebSocketTransportSettings)o).CreateNotificationOnConnection = (bool)v) },
                { "KeepAliveInterval", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("KeepAliveInterval", typeof(global::System.TimeSpan), static o => (((global::CoreWCF.Channels.WebSocketTransportSettings)o).KeepAliveInterval), static (o, v) => ((global::CoreWCF.Channels.WebSocketTransportSettings)o).KeepAliveInterval = (global::System.TimeSpan)v) },
                { "SubProtocol", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("SubProtocol", typeof(string), static o => (((global::CoreWCF.Channels.WebSocketTransportSettings)o).SubProtocol), static (o, v) => ((global::CoreWCF.Channels.WebSocketTransportSettings)o).SubProtocol = (string)v) },
                { "DisablePayloadMasking", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("DisablePayloadMasking", typeof(bool), static o => (((global::CoreWCF.Channels.WebSocketTransportSettings)o).DisablePayloadMasking), static (o, v) => ((global::CoreWCF.Channels.WebSocketTransportSettings)o).DisablePayloadMasking = (bool)v) },
                { "MaxPendingConnections", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("MaxPendingConnections", typeof(int), static o => (((global::CoreWCF.Channels.WebSocketTransportSettings)o).MaxPendingConnections), static (o, v) => ((global::CoreWCF.Channels.WebSocketTransportSettings)o).MaxPendingConnections = (int)v) },
            };

            return new global::CoreWCF.Extensions.Configuration.ConfiguredType(
                typeof(global::CoreWCF.Channels.WebSocketTransportSettings),
                create: static () => new global::CoreWCF.Channels.WebSocketTransportSettings(),
                members: members,
                parse: null,
                addItem: null,
                itemType: null);
        }

        private static readonly global::System.Collections.Generic.Dictionary<string, global::CoreWCF.EnvelopeVersion> s_values_CoreWCF_EnvelopeVersion =
            new global::System.Collections.Generic.Dictionary<string, global::CoreWCF.EnvelopeVersion>(3, global::System.StringComparer.OrdinalIgnoreCase)
            {
                { "None", global::CoreWCF.EnvelopeVersion.None },
                { "Soap11", global::CoreWCF.EnvelopeVersion.Soap11 },
                { "Soap12", global::CoreWCF.EnvelopeVersion.Soap12 },
            };

        private static global::CoreWCF.Extensions.Configuration.ConfiguredType Describe_CoreWCF_EnvelopeVersion()
        {
            var members = new global::System.Collections.Generic.Dictionary<string, global::CoreWCF.Extensions.Configuration.ConfiguredMember>(3, global::System.StringComparer.OrdinalIgnoreCase)
            {
                { "Namespace", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("Namespace", typeof(string), static o => (((global::CoreWCF.EnvelopeVersion)o).Namespace), null) },
                { "DictionaryNamespace", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("DictionaryNamespace", typeof(global::System.Xml.XmlDictionaryString), static o => (((global::CoreWCF.EnvelopeVersion)o).DictionaryNamespace), null) },
                { "NextDestinationActorValue", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("NextDestinationActorValue", typeof(string), static o => (((global::CoreWCF.EnvelopeVersion)o).NextDestinationActorValue), null) },
            };

            return new global::CoreWCF.Extensions.Configuration.ConfiguredType(
                typeof(global::CoreWCF.EnvelopeVersion),
                create: null,
                members: members,
                parse: static s => s_values_CoreWCF_EnvelopeVersion.TryGetValue(s, out global::CoreWCF.EnvelopeVersion value) ? (object)value : throw new global::CoreWCF.Extensions.Configuration.BindingConfigurationException($"'{s}' is not a known CoreWCF.EnvelopeVersion value."),
                addItem: null,
                itemType: null);
        }

        private static readonly global::System.Collections.Generic.Dictionary<string, global::System.Xml.XmlDictionaryReaderQuotas> s_values_System_Xml_XmlDictionaryReaderQuotas =
            new global::System.Collections.Generic.Dictionary<string, global::System.Xml.XmlDictionaryReaderQuotas>(1, global::System.StringComparer.OrdinalIgnoreCase)
            {
                { "Max", global::System.Xml.XmlDictionaryReaderQuotas.Max },
            };

        private static global::CoreWCF.Extensions.Configuration.ConfiguredType Describe_System_Xml_XmlDictionaryReaderQuotas()
        {
            var members = new global::System.Collections.Generic.Dictionary<string, global::CoreWCF.Extensions.Configuration.ConfiguredMember>(6, global::System.StringComparer.OrdinalIgnoreCase)
            {
                { "MaxStringContentLength", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("MaxStringContentLength", typeof(int), static o => (((global::System.Xml.XmlDictionaryReaderQuotas)o).MaxStringContentLength), static (o, v) => ((global::System.Xml.XmlDictionaryReaderQuotas)o).MaxStringContentLength = (int)v) },
                { "MaxArrayLength", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("MaxArrayLength", typeof(int), static o => (((global::System.Xml.XmlDictionaryReaderQuotas)o).MaxArrayLength), static (o, v) => ((global::System.Xml.XmlDictionaryReaderQuotas)o).MaxArrayLength = (int)v) },
                { "MaxBytesPerRead", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("MaxBytesPerRead", typeof(int), static o => (((global::System.Xml.XmlDictionaryReaderQuotas)o).MaxBytesPerRead), static (o, v) => ((global::System.Xml.XmlDictionaryReaderQuotas)o).MaxBytesPerRead = (int)v) },
                { "MaxDepth", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("MaxDepth", typeof(int), static o => (((global::System.Xml.XmlDictionaryReaderQuotas)o).MaxDepth), static (o, v) => ((global::System.Xml.XmlDictionaryReaderQuotas)o).MaxDepth = (int)v) },
                { "MaxNameTableCharCount", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("MaxNameTableCharCount", typeof(int), static o => (((global::System.Xml.XmlDictionaryReaderQuotas)o).MaxNameTableCharCount), static (o, v) => ((global::System.Xml.XmlDictionaryReaderQuotas)o).MaxNameTableCharCount = (int)v) },
                { "ModifiedQuotas", new global::CoreWCF.Extensions.Configuration.ConfiguredMember("ModifiedQuotas", typeof(global::System.Xml.XmlDictionaryReaderQuotaTypes), static o => (((global::System.Xml.XmlDictionaryReaderQuotas)o).ModifiedQuotas), null) },
            };

            return new global::CoreWCF.Extensions.Configuration.ConfiguredType(
                typeof(global::System.Xml.XmlDictionaryReaderQuotas),
                create: static () => new global::System.Xml.XmlDictionaryReaderQuotas(),
                members: members,
                parse: static s => s_values_System_Xml_XmlDictionaryReaderQuotas.TryGetValue(s, out global::System.Xml.XmlDictionaryReaderQuotas value) ? (object)value : throw new global::CoreWCF.Extensions.Configuration.BindingConfigurationException($"'{s}' is not a known System.Xml.XmlDictionaryReaderQuotas value."),
                addItem: null,
                itemType: null);
        }

    }
}
