//HintName: App.MyContext.ServiceModelConfiguration.g.cs
// <auto-generated/>
#nullable disable
#pragma warning disable CS1591
#pragma warning disable CS0612, CS0618

namespace App
{
    public partial class MyContext
    {
        private static readonly global::System.Collections.Generic.Dictionary<string, global::System.Type> s_types =
            new global::System.Collections.Generic.Dictionary<string, global::System.Type>(5, global::System.StringComparer.OrdinalIgnoreCase)
            {
                { "App.EchoService", typeof(global::App.EchoService) },
                { "App.EchoService, GeneratorTests", typeof(global::App.EchoService) },
                { "App.IEcho", typeof(global::App.IEcho) },
                { "App.IEcho, GeneratorTests", typeof(global::App.IEcho) },
                { "echo", typeof(global::App.EchoService) },
            };

        [global::System.Diagnostics.CodeAnalysis.DynamicDependency(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.All, typeof(global::App.EchoService))]
        [global::System.Diagnostics.CodeAnalysis.DynamicDependency(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.All, typeof(global::App.IEcho))]
        public override global::System.Type ResolveType(string name) =>
            name is not null && s_types.TryGetValue(name, out global::System.Type type) ? type : null;

        private static readonly global::System.Collections.Generic.Dictionary<global::System.Type, global::CoreWCF.Extensions.Configuration.ConfiguredType> s_configuredTypes =
            new global::System.Collections.Generic.Dictionary<global::System.Type, global::CoreWCF.Extensions.Configuration.ConfiguredType>(0)
            {
            };

        public override global::CoreWCF.Extensions.Configuration.ConfiguredType GetConfiguredType(global::System.Type type) =>
            type is not null && s_configuredTypes.TryGetValue(type, out global::CoreWCF.Extensions.Configuration.ConfiguredType configured) ? configured : null;

    }
}
