// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace CoreWCF.Extensions.Configuration.Generator;

public sealed partial class ServiceModelConfigurationGenerator
{
    /// <summary>
    /// Writes the partial that completes a user's context.
    /// </summary>
    /// <remarks>
    /// Every reflection call the runtime would otherwise make has a counterpart here, and each one is
    /// ordinary compiled code: <c>typeof</c> instead of <c>Type.GetType</c>, <c>new T()</c> instead of
    /// <c>Activator.CreateInstance</c>, a cast and an assignment instead of <c>PropertyInfo.SetValue</c>,
    /// a closed generic cast instead of <c>MakeGenericType</c>, and a lookup table instead of
    /// <c>TypeDescriptor.GetConverter</c>.
    /// </remarks>
    internal static class Emitter
    {
        private const string Ns = "global::CoreWCF.Extensions.Configuration";
        private const string ConfiguredType = Ns + ".ConfiguredType";
        private const string ConfiguredMember = Ns + ".ConfiguredMember";
        private const string Dictionary = "global::System.Collections.Generic.Dictionary";
        private const string Comparer = "global::System.StringComparer";
        private const string Type = "global::System.Type";

        internal static string HintName(ContextSpec spec) =>
            spec.Namespace is null
                ? $"{spec.ContextName}.ServiceModelConfiguration.g.cs"
                : $"{spec.Namespace}.{spec.ContextName}.ServiceModelConfiguration.g.cs";

        internal static SourceText Emit(ContextSpec spec)
        {
            var source = new StringBuilder();
            var indent = new Indentor();

            source.AppendLine("// <auto-generated/>");
            source.AppendLine("#nullable disable");
            source.AppendLine("#pragma warning disable CS1591");
            // A binding property may be obsolete, and naming one is what the configuration asked for.
            source.AppendLine("#pragma warning disable CS0612, CS0618");
            source.AppendLine();

            if (spec.Namespace is not null)
            {
                source.AppendLine($"namespace {spec.Namespace}");
                source.AppendLine("{");
                indent.Increment();
            }

            source.AppendLine($"{indent}{spec.ContextAccessibility} partial class {spec.ContextName}");
            source.AppendLine($"{indent}{{");
            indent.Increment();

            EmitTypeMap(source, indent, spec);
            EmitConfiguredTypeMap(source, indent, spec);

            foreach (ConfiguredTypeSpec type in spec.Types)
            {
                EmitConfiguredTypeFactory(source, indent, type);
            }

            indent.Decrement();
            source.AppendLine($"{indent}}}");

            if (spec.Namespace is not null)
            {
                indent.Decrement();
                source.AppendLine("}");
            }

            return SourceText.From(source.ToString(), Encoding.UTF8);
        }

        /// <summary>
        /// The name to type map, and the roots that keep a service or contract alive through trimming.
        /// </summary>
        /// <remarks>
        /// The <c>[DynamicDependency]</c> attributes sit on <see cref="ServiceModelConfigurationContext.ResolveType"/>
        /// because a DynamicDependency only takes effect if the member carrying it is itself kept, and an
        /// override of a method the runtime calls always is.
        /// <para>
        /// They are not decoration. CoreWCF's <c>TypeLoader</c> finds a contract's operations by
        /// reflecting over the interface, and nothing calls those methods statically - that is what a
        /// dispatcher is for. Without the dependency the interface arrives trimmed to zero operations and
        /// the host refuses to start.
        /// </para>
        /// </remarks>
        private static void EmitTypeMap(StringBuilder source, Indentor indent, ContextSpec spec)
        {
            source.AppendLine($"{indent}private static readonly {Dictionary}<string, {Type}> s_types =");
            source.AppendLine($"{indent}    new {Dictionary}<string, {Type}>({spec.Names.Count}, {Comparer}.OrdinalIgnoreCase)");
            source.AppendLine($"{indent}    {{");
            foreach (NameSpec name in spec.Names)
            {
                source.AppendLine($"{indent}        {{ {Quote(name.Name)}, typeof({name.TypeExpression}) }},");
            }

            source.AppendLine($"{indent}    }};");
            source.AppendLine();

            if (spec.SupportsDynamicDependency)
            {
                foreach (string rooted in spec.RootedTypes)
                {
                    source.AppendLine(
                        $"{indent}[global::System.Diagnostics.CodeAnalysis.DynamicDependency(" +
                        $"global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.All, typeof({rooted}))]");
                }
            }

            source.AppendLine($"{indent}public override {Type} ResolveType(string name) =>");
            source.AppendLine($"{indent}    name is not null && s_types.TryGetValue(name, out {Type} type) ? type : null;");
            source.AppendLine();
        }

        private static void EmitConfiguredTypeMap(StringBuilder source, Indentor indent, ContextSpec spec)
        {
            source.AppendLine($"{indent}private static readonly {Dictionary}<{Type}, {ConfiguredType}> s_configuredTypes =");
            source.AppendLine($"{indent}    new {Dictionary}<{Type}, {ConfiguredType}>({spec.Types.Count})");
            source.AppendLine($"{indent}    {{");
            foreach (ConfiguredTypeSpec type in spec.Types)
            {
                source.AppendLine($"{indent}        {{ typeof({type.TypeExpression}), Describe_{type.MethodSuffix}() }},");
            }

            source.AppendLine($"{indent}    }};");
            source.AppendLine();

            source.AppendLine($"{indent}public override {ConfiguredType} GetConfiguredType({Type} type) =>");
            source.AppendLine($"{indent}    type is not null && s_configuredTypes.TryGetValue(type, out {ConfiguredType} configured) ? configured : null;");
            source.AppendLine();
        }

        private static void EmitConfiguredTypeFactory(StringBuilder source, Indentor indent, ConfiguredTypeSpec type)
        {
            if (type.Vocabulary.Count > 0)
            {
                EmitVocabulary(source, indent, type);
            }

            source.AppendLine($"{indent}private static {ConfiguredType} Describe_{type.MethodSuffix}()");
            source.AppendLine($"{indent}{{");
            indent.Increment();

            source.AppendLine($"{indent}var members = new {Dictionary}<string, {ConfiguredMember}>({type.Members.Count}, {Comparer}.OrdinalIgnoreCase)");
            source.AppendLine($"{indent}{{");
            foreach (MemberSpec member in type.Members)
            {
                string get = member.CanRead
                    ? $"static o => ((({type.TypeExpression})o).{member.Name})"
                    : "null";

                string set = member.CanWrite
                    ? $"static (o, v) => (({type.TypeExpression})o).{member.Name} = ({member.MemberTypeExpression})v"
                    : "null";

                source.AppendLine(
                    $"{indent}    {{ {Quote(member.Name)}, new {ConfiguredMember}({Quote(member.Name)}, " +
                    $"typeof({member.MemberTypeExpression}), {get}, {set}) }},");
            }

            source.AppendLine($"{indent}}};");
            source.AppendLine();

            source.AppendLine($"{indent}return new {ConfiguredType}(");
            source.AppendLine($"{indent}    typeof({type.TypeExpression}),");
            source.AppendLine($"{indent}    create: {(type.CanCreate ? $"static () => new {type.TypeExpression}()" : "null")},");
            source.AppendLine($"{indent}    members: members,");
            source.AppendLine($"{indent}    parse: {Parse(type)},");
            source.AppendLine($"{indent}    addItem: {AddItem(type)},");
            source.AppendLine($"{indent}    itemType: {(type.CollectionItemTypeExpression is null ? "null" : $"typeof({type.CollectionItemTypeExpression})")});");

            indent.Decrement();
            source.AppendLine($"{indent}}}");
            source.AppendLine();
        }

        /// <summary>
        /// The well-known values of a type that has no TypeConverter, as a lookup table.
        /// </summary>
        /// <remarks>
        /// Compared case-insensitively because the reflective lookup it replaces used
        /// <c>BindingFlags.IgnoreCase</c>, and a configuration file that worked without a context has to
        /// keep working with one.
        /// </remarks>
        private static void EmitVocabulary(StringBuilder source, Indentor indent, ConfiguredTypeSpec type)
        {
            source.AppendLine($"{indent}private static readonly {Dictionary}<string, {type.TypeExpression}> s_values_{type.MethodSuffix} =");
            source.AppendLine($"{indent}    new {Dictionary}<string, {type.TypeExpression}>({type.Vocabulary.Count}, {Comparer}.OrdinalIgnoreCase)");
            source.AppendLine($"{indent}    {{");
            foreach (VocabularySpec value in type.Vocabulary)
            {
                source.AppendLine($"{indent}        {{ {Quote(value.Name)}, {value.Expression} }},");
            }

            source.AppendLine($"{indent}    }};");
            source.AppendLine();
        }

        private static string Parse(ConfiguredTypeSpec type)
        {
            // A type carrying its own converter is asked to convert, exactly as TypeDescriptor would have
            // arranged - the difference being that the converter is constructed rather than discovered.
            if (type.ConverterTypeExpression is not null)
            {
                return $"static s => new {type.ConverterTypeExpression}().ConvertFromInvariantString(s)";
            }

            if (type.Vocabulary.Count == 0)
            {
                return "null";
            }

            return $"static s => s_values_{type.MethodSuffix}.TryGetValue(s, out {type.TypeExpression} value) " +
                   $"? (object)value " +
                   $": throw new {Ns}.BindingConfigurationException($\"'{{s}}' is not a known {type.TypeExpression.Replace("global::", string.Empty)} value.\")";
        }

        /// <summary>
        /// Appending to a collection through a closed generic cast.
        /// </summary>
        /// <remarks>
        /// This is the one call in the package NativeAOT cannot make at all rather than merely warn
        /// about: the reflective form constructs <c>ICollection&lt;T&gt;</c> at run time, which is IL3050.
        /// </remarks>
        private static string AddItem(ConfiguredTypeSpec type) =>
            type.CollectionItemTypeExpression is null
                ? "null"
                : $"static (c, i) => ((global::System.Collections.Generic.ICollection<{type.CollectionItemTypeExpression}>)c)" +
                  $".Add(({type.CollectionItemTypeExpression})i)";

        private static string Quote(string value) => $"\"{value.Replace("\\", "\\\\").Replace("\"", "\\\"")}\"";
    }
}
